arr.push(new Data("Acalanes Ridge", "California", 88, 56, 18));
arr.push(new Data("Acampo", "California", 92, 55, 19));
arr.push(new Data("Acton", "California", 97, 58, 9));
arr.push(new Data("Adelanto", "California", 97, 57, 6));
arr.push(new Data("Adin", "California", 87, 42, 14));
arr.push(new Data("Agoura Hills", "California", 91, 67, 16));
arr.push(new Data("Agua Dulce", "California", 96, 60, 19));
arr.push(new Data("Aguanga", "California", 96, 63, 21));
arr.push(new Data("Ahwahnee", "California", 94, 55, 30));
arr.push(new Data("Airport", "California", 93, 55, 13));
arr.push(new Data("Alameda", "California", 73, 58, 22));
arr.push(new Data("Alamo", "California", 83, 57, 23));
arr.push(new Data("Albany", "California", 73, 58, 25));
arr.push(new Data("Albion", "California", 81, 54, 40));
arr.push(new Data("Alhambra", "California", 87, 69, 16));
arr.push(new Data("Alhambra Valley", "California", 88, 56, 18));
arr.push(new Data("Aliso Viejo", "California", 86, 66, 14));
arr.push(new Data("Allendale", "California", 94, 56, 26));
arr.push(new Data("Allensworth", "California", 98, 57, 9));
arr.push(new Data("Alondra Park", "California", 77, 65, 14));
arr.push(new Data("Alpaugh", "California", 97, 56, 8));
arr.push(new Data("Alpine", "California", 89, 65, 16));
arr.push(new Data("Alpine Village", "California", 76, 39, 33));
arr.push(new Data("Alta", "California", 83, 47, 69));
arr.push(new Data("Alta Sierra", "California", 89, 52, 50));
arr.push(new Data("Altadena", "California", 88, 67, 23));
arr.push(new Data("Alto", "California", 77, 55, 41));
arr.push(new Data("Alturas", "California", 87, 41, 13));
arr.push(new Data("Alum Rock", "California", 81, 58, 16));
arr.push(new Data("Amador City", "California", 93, 54, 30));
arr.push(new Data("American Canyon", "California", 84, 56, 24));
arr.push(new Data("Amesti", "California", 74, 61, 25));
arr.push(new Data("Anaheim", "California", 86, 69, 14));
arr.push(new Data("Anchor Bay", "California", 91, 56, 40));
arr.push(new Data("Anderson", "California", 96, 54, 34));
arr.push(new Data("Angels", "California", 93, 55, 33));
arr.push(new Data("Angwin", "California", 88, 54, 40));
arr.push(new Data("Antelope", "California", 93, 54, 21));
arr.push(new Data("Antioch", "California", 89, 56, 15));
arr.push(new Data("Anza", "California", 88, 55, 16));
arr.push(new Data("Apple Valley", "California", 97, 58, 14));
arr.push(new Data("Aptos", "California", 74, 61, 25));
arr.push(new Data("Aptos Hills-Larkin Valley", "California", 74, 61, 25));
arr.push(new Data("Arbuckle", "California", 93, 54, 24));
arr.push(new Data("Arcadia", "California", 87, 68, 16));
arr.push(new Data("Arcata", "California", 66, 55, 46));
arr.push(new Data("Arden-Arcade", "California", 92, 54, 20));
arr.push(new Data("Armona", "California", 95, 54, 9));
arr.push(new Data("Arnold", "California", 84, 47, 50));
arr.push(new Data("Aromas", "California", 81, 60, 18));
arr.push(new Data("Arroyo Grande", "California", 74, 62, 20));
arr.push(new Data("Artesia", "California", 83, 67, 14));
arr.push(new Data("Artois", "California", 94, 56, 24));
arr.push(new Data("Arvin", "California", 96, 57, 7));
arr.push(new Data("Ashland", "California", 74, 57, 21));
arr.push(new Data("Aspen Springs", "California", 77, 41, 15));
arr.push(new Data("Atascadero", "California", 88, 60, 21));
arr.push(new Data("Atherton", "California", 79, 58, 17));
arr.push(new Data("Atwater", "California", 93, 54, 13));
arr.push(new Data("Auberry", "California", 94, 55, 30));
arr.push(new Data("Auburn", "California", 92, 55, 38));
arr.push(new Data("Auburn Lake Trails", "California", 90, 54, 39));
arr.push(new Data("August", "California", 92, 55, 17));
arr.push(new Data("Avalon", "California", 80, 62, 14));
arr.push(new Data("Avenal", "California", 96, 58, 8));
arr.push(new Data("Avery", "California", 88, 50, 46));
arr.push(new Data("Avilla Beach", "California", 75, 62, 20));
arr.push(new Data("Avocado Heights", "California", 89, 69, 16));
arr.push(new Data("Azusa", "California", 91, 67, 20));
arr.push(new Data("Baker", "California", 107, 61, 5));
arr.push(new Data("Bakersfield", "California", 96, 57, 7));
arr.push(new Data("Baldwin Park", "California", 89, 69, 16));
arr.push(new Data("Ballard", "California", 84, 65, 19));
arr.push(new Data("Ballico", "California", 93, 54, 13));
arr.push(new Data("Bangor", "California", 93, 55, 31));
arr.push(new Data("Banning", "California", 98, 65, 16));
arr.push(new Data("Barstow", "California", 100, 59, 5));
arr.push(new Data("Bass Lake", "California", 91, 51, 34));
arr.push(new Data("Bay Point", "California", 88, 56, 16));
arr.push(new Data("Bayview (Contra Costa Cnty)", "California", 78, 56, 36));
arr.push(new Data("Bayview (Humboldt Cnty)", "California", 66, 55, 46));
arr.push(new Data("Beale AFB", "California", 94, 55, 22));
arr.push(new Data("Bear Creek", "California", 94, 54, 12));
arr.push(new Data("Bear Valley (Alpine Cnty)", "California", 84, 47, 50));
arr.push(new Data("Bear Valley (Mariposa Cnty)", "California", 92, 55, 31));
arr.push(new Data("Bear Valley Springs", "California", 86, 50, 12));
arr.push(new Data("Beaumont", "California", 98, 63, 23));
arr.push(new Data("Beckwourth", "California", 84, 42, 18));
arr.push(new Data("Bell", "California", 84, 68, 15));
arr.push(new Data("Bell Canyon", "California", 95, 68, 18));
arr.push(new Data("Bell Gardens", "California", 84, 68, 15));
arr.push(new Data("Bella Vista", "California", 96, 53, 48));
arr.push(new Data("Bellflower", "California", 83, 67, 14));
arr.push(new Data("Belmont", "California", 80, 59, 27));
arr.push(new Data("Belvedere", "California", 77, 55, 37));
arr.push(new Data("Ben Lomond", "California", 82, 60, 36));
arr.push(new Data("Benbow", "California", 80, 52, 67));
arr.push(new Data("Bend", "California", 95, 55, 28));
arr.push(new Data("Benicia", "California", 83, 57, 22));
arr.push(new Data("Benton", "California", 90, 46, 7));
arr.push(new Data("Bermuda Dunes", "California", 107, 71, 3));
arr.push(new Data("Berry Creek", "California", 91, 53, 63));
arr.push(new Data("Bertsch-Oceanview", "California", 64, 54, 71));
arr.push(new Data("Bethel Island", "California", 92, 55, 15));
arr.push(new Data("Beverly Hills", "California", 82, 66, 16));
arr.push(new Data("Bieber", "California", 85, 41, 14));
arr.push(new Data("Big Bear City", "California", 80, 48, 20));
arr.push(new Data("Big Bear Lake", "California", 80, 48, 21));
arr.push(new Data("Big Bend", "California", 89, 46, 34));
arr.push(new Data("Big Creek", "California", 79, 47, 37));
arr.push(new Data("Big Lagoon", "California", 74, 52, 56));
arr.push(new Data("Big Pine", "California", 96, 53, 5));
arr.push(new Data("Big River", "California", 108, 66, 5));
arr.push(new Data("Biggs", "California", 94, 55, 28));
arr.push(new Data("Biola", "California", 96, 55, 12));
arr.push(new Data("Bishop", "California", 94, 50, 5));
arr.push(new Data("Black Point-Green Point", "California", 81, 55, 37));
arr.push(new Data("Blackhawk", "California", 84, 57, 19));
arr.push(new Data("Blacklake", "California", 78, 64, 17));
arr.push(new Data("Blairsden", "California", 85, 43, 38));
arr.push(new Data("Bloomfield", "California", 84, 57, 30));
arr.push(new Data("Bloomington", "California", 95, 67, 14));
arr.push(new Data("Blue Lake", "California", 75, 53, 49));
arr.push(new Data("Bluewater", "California", 108, 66, 5));
arr.push(new Data("Blythe", "California", 107, 66, 4));
arr.push(new Data("Bodega", "California", 76, 56, 45));
arr.push(new Data("Bodega Bay", "California", 71, 57, 40));
arr.push(new Data("Bodfish", "California", 94, 57, 15));
arr.push(new Data("Bolinas", "California", 77, 55, 41));
arr.push(new Data("Bombay Beach", "California", 107, 70, 3));
arr.push(new Data("Bonadelle Ranchos-Madera Ranchos", "California", 96, 55, 13));
arr.push(new Data("Bonita", "California", 77, 67, 10));
arr.push(new Data("Bonny Doon", "California", 79, 61, 34));
arr.push(new Data("Bonsall", "California", 81, 66, 14));
arr.push(new Data("Boonville", "California", 91, 56, 40));
arr.push(new Data("Bootjack", "California", 92, 55, 31));
arr.push(new Data("Boron", "California", 98, 58, 8));
arr.push(new Data("Boronda", "California", 72, 61, 17));
arr.push(new Data("Borrego Springs", "California", 104, 69, 8));
arr.push(new Data("Bostonia", "California", 90, 69, 15));
arr.push(new Data("Boulder Creek", "California", 81, 59, 36));
arr.push(new Data("Boulevard", "California", 88, 56, 20));
arr.push(new Data("Bowles", "California", 96, 55, 12));
arr.push(new Data("Boyes Hot Springs", "California", 85, 57, 31));
arr.push(new Data("Bradbury", "California", 90, 67, 23));
arr.push(new Data("Bradley", "California", 88, 60, 19));
arr.push(new Data("Brawley", "California", 106, 69, 3));
arr.push(new Data("Brea", "California", 88, 69, 15));
arr.push(new Data("Brentwood", "California", 90, 55, 15));
arr.push(new Data("Bret Harte", "California", 93, 55, 13));
arr.push(new Data("Bridgeport", "California", 81, 42, 16));
arr.push(new Data("Brisbane", "California", 71, 57, 22));
arr.push(new Data("Broadmoor", "California", 68, 57, 26));
arr.push(new Data("Brookdale", "California", 82, 60, 36));
arr.push(new Data("Brooktrails", "California", 88, 53, 47));
arr.push(new Data("Buck Meadows", "California", 90, 52, 40));
arr.push(new Data("Buckhorn", "California", 91, 52, 48));
arr.push(new Data("Buellton", "California", 84, 65, 19));
arr.push(new Data("Buena Park", "California", 85, 68, 14));
arr.push(new Data("Buena Vista", "California", 94, 55, 21));
arr.push(new Data("Burbank", "California", 87, 67, 17));
arr.push(new Data("Burlingame", "California", 73, 58, 23));
arr.push(new Data("Burney", "California", 89, 45, 24));
arr.push(new Data("Burnt Ranch", "California", 95, 48, 42));
arr.push(new Data("Butte Creek Canyon", "California", 94, 55, 30));
arr.push(new Data("Butte Meadows", "California", 90, 52, 66));
arr.push(new Data("Butte Valley", "California", 94, 55, 34));
arr.push(new Data("Buttonwillow", "California", 97, 57, 7));
arr.push(new Data("Byron", "California", 91, 55, 14));
arr.push(new Data("Bystrom", "California", 93, 55, 13));
arr.push(new Data("Cabazon", "California", 99, 67, 12));
arr.push(new Data("Calabasas", "California", 91, 67, 17));
arr.push(new Data("Calexico", "California", 106, 69, 3));
arr.push(new Data("California City", "California", 98, 58, 6));
arr.push(new Data("California Hot Springs", "California", 97, 58, 10));
arr.push(new Data("California Pines", "California", 87, 41, 13));
arr.push(new Data("Calimesa", "California", 97, 65, 22));
arr.push(new Data("Calipatria", "California", 106, 69, 3));
arr.push(new Data("Calistoga", "California", 88, 58, 37));
arr.push(new Data("Callender", "California", 74, 62, 20));
arr.push(new Data("Calpella", "California", 91, 55, 41));
arr.push(new Data("Calpine", "California", 83, 43, 37));
arr.push(new Data("Calwa", "California", 96, 55, 12));
arr.push(new Data("Camanche North Shore", "California", 94, 55, 21));
arr.push(new Data("Camanche Village", "California", 94, 55, 21));
arr.push(new Data("Camarillo", "California", 78, 67, 16));
arr.push(new Data("Cambria", "California", 74, 64, 20));
arr.push(new Data("Cambrian Park", "California", 83, 58, 18));
arr.push(new Data("Cameron Park", "California", 92, 54, 37));
arr.push(new Data("Camino", "California", 91, 52, 52));
arr.push(new Data("Camino Tassajara", "California", 84, 57, 19));
arr.push(new Data("Camp Pendleton North", "California", 79, 65, 13));
arr.push(new Data("Camp Pendleton South", "California", 78, 65, 13));
arr.push(new Data("Campbell", "California", 83, 58, 18));
arr.push(new Data("Campo", "California", 94, 63, 18));
arr.push(new Data("Camptonville", "California", 88, 49, 62));
arr.push(new Data("Canby", "California", 87, 41, 14));
arr.push(new Data("Cantua Creek", "California", 95, 55, 9));
arr.push(new Data("Canyon Lake", "California", 99, 67, 12));
arr.push(new Data("Capitola", "California", 74, 61, 25));
arr.push(new Data("Carlsbad", "California", 75, 64, 12));
arr.push(new Data("Carmel Valley Village", "California", 73, 60, 21));
arr.push(new Data("Carmel-by-the-Sea", "California", 68, 59, 18));
arr.push(new Data("Carmichael", "California", 92, 54, 20));
arr.push(new Data("Carnelian Bay", "California", 78, 40, 29));
arr.push(new Data("Carpinteria", "California", 74, 63, 18));
arr.push(new Data("Carrick", "California", 87, 45, 40));
arr.push(new Data("Carson", "California", 80, 66, 14));
arr.push(new Data("Cartago", "California", 99, 56, 7));
arr.push(new Data("Caruthers", "California", 95, 54, 9));
arr.push(new Data("Casa Conejo", "California", 92, 67, 17));
arr.push(new Data("Casa de Oro-Mount Helix", "California", 86, 68, 13));
arr.push(new Data("Casmalia", "California", 75, 64, 16));
arr.push(new Data("Caspar", "California", 75, 53, 41));
arr.push(new Data("Cassel", "California", 89, 45, 24));
arr.push(new Data("Castaic", "California", 91, 64, 18));
arr.push(new Data("Castle Hill", "California", 83, 57, 23));
arr.push(new Data("Castro Valley", "California", 77, 57, 21));
arr.push(new Data("Castroville", "California", 72, 61, 17));
arr.push(new Data("Cathedral City", "California", 107, 69, 5));
arr.push(new Data("Catheys Valley", "California", 92, 55, 30));
arr.push(new Data("Cayucos", "California", 75, 63, 20));
arr.push(new Data("Cazadero", "California", 78, 56, 51));
arr.push(new Data("Cedar Ridge", "California", 90, 52, 41));
arr.push(new Data("Cedarville", "California", 86, 40, 15));
arr.push(new Data("Centerville", "California", 98, 56, 15));
arr.push(new Data("Ceres", "California", 94, 56, 13));
arr.push(new Data("Cerritos", "California", 83, 67, 14));
arr.push(new Data("Chalfant", "California", 94, 50, 5));
arr.push(new Data("Challenge-Brownsville", "California", 89, 52, 52));
arr.push(new Data("Channel Islands Beach", "California", 74, 65, 15));
arr.push(new Data("Charter Oak", "California", 91, 67, 19));
arr.push(new Data("Cherokee", "California", 94, 55, 34));
arr.push(new Data("Cherokee Strip", "California", 97, 57, 7));
arr.push(new Data("Cherry Valley", "California", 98, 63, 23));
arr.push(new Data("Cherryland", "California", 76, 57, 22));
arr.push(new Data("Chester", "California", 83, 41, 41));
arr.push(new Data("Chico", "California", 93, 55, 28));
arr.push(new Data("China Lake Acres", "California", 102, 59, 5));
arr.push(new Data("Chinese Camp", "California", 94, 56, 33));
arr.push(new Data("Chino", "California", 93, 67, 17));
arr.push(new Data("Chino Hills", "California", 93, 67, 15));
arr.push(new Data("Chowchilla", "California", 95, 54, 12));
arr.push(new Data("Chualar", "California", 87, 60, 18));
arr.push(new Data("Chula Vista", "California", 80, 67, 11));
arr.push(new Data("Citrus", "California", 90, 67, 19));
arr.push(new Data("Citrus Heights", "California", 93, 54, 21));
arr.push(new Data("Claremont", "California", 94, 67, 22));
arr.push(new Data("Clarksburg", "California", 92, 54, 19));
arr.push(new Data("Clay", "California", 91, 55, 19));
arr.push(new Data("Clayton", "California", 88, 57, 19));
arr.push(new Data("Clear Creek", "California", 83, 41, 41));
arr.push(new Data("Clearlake", "California", 90, 55, 33));
arr.push(new Data("Clearlake Oaks", "California", 90, 55, 32));
arr.push(new Data("Clearlake Riviera", "California", 89, 54, 41));
arr.push(new Data("Cleone", "California", 68, 52, 51));
arr.push(new Data("Clio", "California", 84, 43, 37));
arr.push(new Data("Clovis", "California", 98, 56, 13));
arr.push(new Data("Clyde", "California", 88, 56, 18));
arr.push(new Data("Coachella", "California", 107, 71, 3));
arr.push(new Data("Coalinga", "California", 97, 58, 8));
arr.push(new Data("Coarsegold", "California", 94, 54, 28));
arr.push(new Data("Cobb", "California", 89, 54, 38));
arr.push(new Data("Coffee Creek", "California", 89, 44, 28));
arr.push(new Data("Cohasset", "California", 93, 55, 27));
arr.push(new Data("Cold Springs (El Dorado Cnty)", "California", 92, 53, 39));
arr.push(new Data("Cold Springs (Tuolumne Cnty)", "California", 84, 46, 46));
arr.push(new Data("Coleville", "California", 74, 38, 42));
arr.push(new Data("Colfax", "California", 87, 51, 47));
arr.push(new Data("College City", "California", 93, 54, 24));
arr.push(new Data("Collierville", "California", 92, 55, 19));
arr.push(new Data("Colma", "California", 68, 57, 25));
arr.push(new Data("Coloma", "California", 92, 53, 39));
arr.push(new Data("Colton", "California", 96, 68, 12));
arr.push(new Data("Columbia", "California", 90, 52, 41));
arr.push(new Data("Colusa", "California", 93, 55, 24));
arr.push(new Data("Commerce", "California", 85, 69, 15));
arr.push(new Data("Comptche", "California", 82, 54, 40));
arr.push(new Data("Compton", "California", 78, 66, 14));
arr.push(new Data("Concord", "California", 88, 56, 18));
arr.push(new Data("Concow", "California", 94, 55, 34));
arr.push(new Data("Contra Costa Centre", "California", 88, 56, 18));
arr.push(new Data("Copperopolis", "California", 94, 56, 29));
arr.push(new Data("Corcoran", "California", 96, 55, 9));
arr.push(new Data("Corning", "California", 94, 55, 25));
arr.push(new Data("Corona", "California", 95, 67, 12));
arr.push(new Data("Coronado", "California", 76, 65, 11));
arr.push(new Data("Coronita", "California", 95, 67, 12));
arr.push(new Data("Corralitos", "California", 74, 61, 25));
arr.push(new Data("Corte Madera", "California", 77, 55, 41));
arr.push(new Data("Costa Mesa", "California", 79, 66, 12));
arr.push(new Data("Cotati", "California", 83, 58, 34));
arr.push(new Data("Coto de Caza", "California", 97, 67, 13));
arr.push(new Data("Cottonwood", "California", 96, 54, 34));
arr.push(new Data("Coultervillle", "California", 91, 54, 36));
arr.push(new Data("Country Club", "California", 92, 55, 17));
arr.push(new Data("Courtland", "California", 92, 54, 19));
arr.push(new Data("Covelo", "California", 90, 53, 46));
arr.push(new Data("Covina", "California", 90, 68, 18));
arr.push(new Data("Cowan", "California", 93, 55, 13));
arr.push(new Data("Crescent City", "California", 64, 54, 71));
arr.push(new Data("Crescent Mills", "California", 86, 44, 49));
arr.push(new Data("Cressey", "California", 93, 54, 13));
arr.push(new Data("Crest", "California", 90, 69, 15));
arr.push(new Data("Creston", "California", 89, 60, 24));
arr.push(new Data("C-Road", "California", 85, 43, 38));
arr.push(new Data("Crockett", "California", 88, 56, 18));
arr.push(new Data("Cromberg", "California", 85, 43, 38));
arr.push(new Data("Crowley Lake", "California", 77, 41, 15));
arr.push(new Data("Crows Landing", "California", 94, 56, 12));
arr.push(new Data("Cudahy", "California", 84, 68, 15));
arr.push(new Data("Culver City", "California", 77, 65, 14));
arr.push(new Data("Cutler", "California", 95, 55, 12));
arr.push(new Data("Cutten", "California", 66, 55, 46));
arr.push(new Data("Cypress", "California", 85, 68, 14));
arr.push(new Data("Daly City", "California", 68, 57, 26));
arr.push(new Data("Dana Point", "California", 85, 67, 14));
arr.push(new Data("Danville", "California", 84, 57, 19));
arr.push(new Data("Daphnedale Park", "California", 87, 41, 13));
arr.push(new Data("Darwin", "California", 102, 59, 5));
arr.push(new Data("Davenport", "California", 82, 60, 36));
arr.push(new Data("Davis", "California", 93, 54, 21));
arr.push(new Data("Day Valley", "California", 74, 61, 25));
arr.push(new Data("Deer Park", "California", 89, 58, 37));
arr.push(new Data("Del Aire", "California", 77, 65, 14));
arr.push(new Data("Del Mar", "California", 75, 64, 12));
arr.push(new Data("Del Monte Forest", "California", 68, 59, 18));
arr.push(new Data("Del Rey", "California", 96, 55, 12));
arr.push(new Data("Del Rey Oaks", "California", 68, 59, 18));
arr.push(new Data("Del Rio", "California", 93, 55, 13));
arr.push(new Data("Delano", "California", 98, 57, 8));
arr.push(new Data("Delft Colony", "California", 94, 54, 10));
arr.push(new Data("Delhi", "California", 94, 56, 12));
arr.push(new Data("Delleker", "California", 84, 42, 18));
arr.push(new Data("Denair", "California", 93, 55, 12));
arr.push(new Data("Derby Acres", "California", 95, 57, 7));
arr.push(new Data("Descanso", "California", 87, 54, 21));
arr.push(new Data("Desert Center", "California", 105, 65, 4));
arr.push(new Data("Desert Edge", "California", 107, 67, 6));
arr.push(new Data("Desert Hot Springs", "California", 105, 68, 5));
arr.push(new Data("Desert Palms", "California", 107, 69, 5));
arr.push(new Data("Desert Shores", "California", 107, 71, 3));
arr.push(new Data("Desert View Highlands", "California", 98, 58, 9));
arr.push(new Data("Diablo", "California", 84, 57, 19));
arr.push(new Data("Diablo Grande", "California", 94, 56, 12));
arr.push(new Data("Diamond Bar", "California", 93, 67, 19));
arr.push(new Data("Diamond Springs", "California", 92, 54, 38));
arr.push(new Data("Dillon Beach", "California", 76, 57, 37));
arr.push(new Data("Dinuba", "California", 94, 54, 10));
arr.push(new Data("Discovery Bay", "California", 92, 55, 15));
arr.push(new Data("Dixon", "California", 93, 55, 23));
arr.push(new Data("Dixon Lane-Meadow Creek", "California", 94, 50, 5));
arr.push(new Data("Dobbins", "California", 91, 54, 50));
arr.push(new Data("Dogtown", "California", 92, 55, 19));
arr.push(new Data("Dollar Point", "California", 78, 40, 28));
arr.push(new Data("Dorrington", "California", 84, 47, 50));
arr.push(new Data("Dorris", "California", 86, 40, 18));
arr.push(new Data("Dos Palos", "California", 94, 55, 12));
arr.push(new Data("Dos Palos Y", "California", 94, 55, 12));
arr.push(new Data("Douglas City", "California", 93, 45, 37));
arr.push(new Data("Downey", "California", 86, 69, 14));
arr.push(new Data("Downieville", "California", 85, 46, 54));
arr.push(new Data("Doyle", "California", 85, 42, 14));
arr.push(new Data("Drytown", "California", 93, 54, 30));
arr.push(new Data("Duarte", "California", 89, 68, 17));
arr.push(new Data("Dublin", "California", 84, 57, 19));
arr.push(new Data("Ducor", "California", 97, 58, 10));
arr.push(new Data("Dunnigan", "California", 94, 55, 24));
arr.push(new Data("Dunsmuir", "California", 90, 48, 50));
arr.push(new Data("Durham", "California", 94, 55, 29));
arr.push(new Data("Dustin Acres", "California", 96, 56, 6));
arr.push(new Data("Dutch Flat", "California", 89, 49, 55));
arr.push(new Data("Eagleville", "California", 86, 40, 15));
arr.push(new Data("Earlimart", "California", 98, 57, 9));
arr.push(new Data("East Foothills", "California", 81, 58, 16));
arr.push(new Data("East Hemet", "California", 99, 67, 12));
arr.push(new Data("East Los Angeles", "California", 87, 69, 15));
arr.push(new Data("East Nicolaus", "California", 94, 54, 21));
arr.push(new Data("East Oakdale", "California", 93, 55, 13));
arr.push(new Data("East Orosi", "California", 95, 56, 15));
arr.push(new Data("East Palo Alto", "California", 79, 58, 17));
arr.push(new Data("East Pasadena", "California", 89, 67, 21));
arr.push(new Data("East Porterville", "California", 97, 58, 13));
arr.push(new Data("East Quincy", "California", 86, 45, 62));
arr.push(new Data("East Rancho Dominguez", "California", 80, 66, 14));
arr.push(new Data("East Richmond Heights", "California", 76, 57, 33));
arr.push(new Data("East San Gabriel", "California", 89, 68, 16));
arr.push(new Data("East Shore", "California", 83, 41, 41));
arr.push(new Data("East Sonora", "California", 90, 52, 41));
arr.push(new Data("East Tulare Villa", "California", 95, 55, 10));
arr.push(new Data("East Whittier", "California", 88, 70, 15));
arr.push(new Data("Easton", "California", 96, 55, 12));
arr.push(new Data("Eastvale", "California", 93, 67, 13));
arr.push(new Data("Edgewood", "California", 87, 45, 40));
arr.push(new Data("Edmundson Acres", "California", 96, 57, 7));
arr.push(new Data("Edna", "California", 75, 62, 20));
arr.push(new Data("Edwards AFB", "California", 98, 58, 7));
arr.push(new Data("El Cajon", "California", 88, 69, 14));
arr.push(new Data("El Centro", "California", 106, 69, 3));
arr.push(new Data("El Cerrito", "California", 72, 58, 25));
arr.push(new Data("El Cerrito CDP", "California", 94, 67, 13));
arr.push(new Data("El Dorado Hills", "California", 94, 56, 30));
arr.push(new Data("El Granada", "California", 73, 58, 24));
arr.push(new Data("El Monte", "California", 87, 69, 16));
arr.push(new Data("El Nido", "California", 94, 55, 12));
arr.push(new Data("El Portal", "California", 91, 54, 30));
arr.push(new Data("El Rancho", "California", 96, 57, 12));
arr.push(new Data("El Rio", "California", 74, 65, 15));
arr.push(new Data("El Segundo", "California", 77, 65, 14));
arr.push(new Data("El Sobrante (Contra Costa Cnty)", "California", 78, 57, 24));
arr.push(new Data("El Sobrante (Riverside Cnty)", "California", 95, 68, 11));
arr.push(new Data("El Verano", "California", 85, 57, 31));
arr.push(new Data("Eldridge", "California", 86, 57, 33));
arr.push(new Data("Elizabeth Lake", "California", 94, 55, 13));
arr.push(new Data("Elk Creek", "California", 94, 56, 23));
arr.push(new Data("Elk Grove", "California", 92, 54, 20));
arr.push(new Data("Elkhorn", "California", 72, 61, 17));
arr.push(new Data("Elmira", "California", 94, 56, 25));
arr.push(new Data("Elverta", "California", 92, 54, 20));
arr.push(new Data("Emerald Lake Hills", "California", 83, 54, 37));
arr.push(new Data("Emeryville", "California", 73, 58, 23));
arr.push(new Data("Empire", "California", 93, 56, 13));
arr.push(new Data("Encinitas", "California", 74, 64, 12));
arr.push(new Data("Escalon", "California", 93, 55, 13));
arr.push(new Data("Escondido", "California", 88, 69, 14));
arr.push(new Data("Esparto", "California", 95, 56, 24));
arr.push(new Data("Etna", "California", 89, 44, 23));
arr.push(new Data("Eucalyptus Hills", "California", 90, 69, 14));
arr.push(new Data("Eureka", "California", 66, 55, 46));
arr.push(new Data("Exeter", "California", 95, 56, 13));
arr.push(new Data("Fair Oaks", "California", 93, 55, 21));
arr.push(new Data("Fairbanks Ranch", "California", 83, 67, 12));
arr.push(new Data("Fairfax", "California", 79, 55, 41));
arr.push(new Data("Fairfield", "California", 90, 56, 25));
arr.push(new Data("Fairmead", "California", 95, 54, 12));
arr.push(new Data("Fairview", "California", 76, 57, 22));
arr.push(new Data("Fall River Mills", "California", 89, 45, 21));
arr.push(new Data("Fallbrook", "California", 87, 67, 14));
arr.push(new Data("Farmersville", "California", 95, 56, 13));
arr.push(new Data("Farmington", "California", 93, 55, 15));
arr.push(new Data("Fellows", "California", 95, 57, 7));
arr.push(new Data("Felton", "California", 82, 60, 36));
arr.push(new Data("Ferndale", "California", 70, 53, 49));
arr.push(new Data("Fetters Hot Springs-Agua Caliente", "California", 85, 57, 31));
arr.push(new Data("Fiddletown", "California", 92, 52, 39));
arr.push(new Data("Fieldbrook", "California", 65, 54, 50));
arr.push(new Data("Fields Landing", "California", 66, 55, 46));
arr.push(new Data("Fillmore", "California", 86, 67, 19));
arr.push(new Data("Firebaugh", "California", 95, 55, 11));
arr.push(new Data("Fish Camp", "California", 83, 47, 39));
arr.push(new Data("Florence-Graham", "California", 79, 66, 14));
arr.push(new Data("Florin", "California", 92, 54, 20));
arr.push(new Data("Floriston", "California", 83, 41, 31));
arr.push(new Data("Flournoy", "California", 94, 56, 26));
arr.push(new Data("Folsom", "California", 93, 55, 21));
arr.push(new Data("Fontana", "California", 95, 67, 14));
arr.push(new Data("Foothill Farms", "California", 93, 54, 21));
arr.push(new Data("Forbestown", "California", 89, 49, 65));
arr.push(new Data("Ford City", "California", 96, 56, 6));
arr.push(new Data("Forest Meadows", "California", 90, 51, 44));
arr.push(new Data("Forest Ranch", "California", 90, 52, 66));
arr.push(new Data("Foresthill", "California", 90, 51, 54));
arr.push(new Data("Forestville", "California", 85, 57, 41));
arr.push(new Data("Fort Bidwell", "California", 86, 40, 13));
arr.push(new Data("Fort Bragg", "California", 68, 52, 51));
arr.push(new Data("Fort Irwin", "California", 96, 53, 6));
arr.push(new Data("Fort Jones", "California", 89, 44, 22));
arr.push(new Data("Fort Washington", "California", 98, 56, 13));
arr.push(new Data("Fortuna", "California", 70, 53, 49));
arr.push(new Data("Foster City", "California", 78, 58, 19));
arr.push(new Data("Fountain Valley", "California", 80, 66, 12));
arr.push(new Data("Fowler", "California", 96, 55, 12));
arr.push(new Data("Franklin (Merced Cnty)", "California", 94, 54, 13));
arr.push(new Data("Franklin (Sacramento Cnty)", "California", 91, 54, 20));
arr.push(new Data("Frazier Park", "California", 87, 52, 12));
arr.push(new Data("Freedom", "California", 74, 61, 25));
arr.push(new Data("Freeport", "California", 92, 54, 20));
arr.push(new Data("Fremont", "California", 78, 58, 16));
arr.push(new Data("French Camp", "California", 92, 55, 17));
arr.push(new Data("French Gulch", "California", 93, 48, 40));
arr.push(new Data("French Valley", "California", 99, 67, 12));
arr.push(new Data("Fresno", "California", 97, 56, 13));
arr.push(new Data("Friant", "California", 98, 56, 16));
arr.push(new Data("Fruitdale", "California", 81, 58, 16));
arr.push(new Data("Fruitridge Pocket", "California", 92, 54, 20));
arr.push(new Data("Fuller Acres", "California", 96, 57, 7));
arr.push(new Data("Fullerton", "California", 87, 69, 14));
arr.push(new Data("Fulton", "California", 83, 58, 37));
arr.push(new Data("Furnace Creek", "California", 101, 59, 5));
arr.push(new Data("Galt", "California", 92, 55, 19));
arr.push(new Data("Garberville", "California", 80, 52, 67));
arr.push(new Data("Garden Acres", "California", 92, 55, 17));
arr.push(new Data("Garden Farms", "California", 88, 60, 21));
arr.push(new Data("Garden Grove", "California", 84, 68, 13));
arr.push(new Data("Gardena", "California", 77, 65, 14));
arr.push(new Data("Garey", "California", 78, 64, 16));
arr.push(new Data("Garnet", "California", 105, 68, 5));
arr.push(new Data("Gasquet", "California", 66, 54, 26));
arr.push(new Data("Gazelle", "California", 87, 45, 38));
arr.push(new Data("Georgetown", "California", 90, 51, 53));
arr.push(new Data("Gerber", "California", 94, 55, 26));
arr.push(new Data("Geyserville", "California", 90, 57, 45));
arr.push(new Data("Gilroy", "California", 83, 60, 21));
arr.push(new Data("Glen Ellen", "California", 86, 58, 33));
arr.push(new Data("Glendale", "California", 87, 67, 19));
arr.push(new Data("Glendora", "California", 92, 67, 22));
arr.push(new Data("Gold River", "California", 93, 55, 20));
arr.push(new Data("Golden Hills", "California", 86, 50, 12));
arr.push(new Data("Goleta", "California", 74, 63, 18));
arr.push(new Data("Gonzales", "California", 71, 61, 15));
arr.push(new Data("Good Hope", "California", 99, 68, 12));
arr.push(new Data("Goodyears Bar", "California", 85, 47, 65));
arr.push(new Data("Goshen", "California", 94, 54, 10));
arr.push(new Data("Graeagle", "California", 85, 43, 38));
arr.push(new Data("Grand Terrace", "California", 96, 68, 12));
arr.push(new Data("Grangeville", "California", 96, 54, 9));
arr.push(new Data("Granite Bay", "California", 93, 55, 21));
arr.push(new Data("Granite Hills", "California", 90, 69, 15));
arr.push(new Data("Grass Valley", "California", 87, 50, 55));
arr.push(new Data("Graton", "California", 83, 58, 37));
arr.push(new Data("Grayson", "California", 94, 56, 12));
arr.push(new Data("Greeley Hill", "California", 91, 54, 36));
arr.push(new Data("Green Acres", "California", 99, 67, 12));
arr.push(new Data("Green Valley (Los Angeles Cnty)", "California", 96, 60, 19));
arr.push(new Data("Green Valley (Solano Cnty)", "California", 84, 56, 24));
arr.push(new Data("Greenacres", "California", 97, 57, 7));
arr.push(new Data("Greenfield", "California", 82, 62, 23));
arr.push(new Data("Greenfield CDP", "California", 96, 57, 7));
arr.push(new Data("Greenhorn", "California", 86, 45, 62));
arr.push(new Data("Greenview", "California", 89, 44, 23));
arr.push(new Data("Greenville", "California", 87, 42, 50));
arr.push(new Data("Grenada", "California", 90, 45, 21));
arr.push(new Data("Gridley", "California", 94, 55, 28));
arr.push(new Data("Grimes", "California", 94, 55, 24));
arr.push(new Data("Grizzly Flats", "California", 91, 53, 52));
arr.push(new Data("Groveland", "California", 90, 53, 39));
arr.push(new Data("Grover Beach", "California", 74, 62, 19));
arr.push(new Data("Guadalupe", "California", 73, 62, 17));
arr.push(new Data("Guerneville", "California", 85, 57, 41));
arr.push(new Data("Guinda", "California", 91, 57, 35));
arr.push(new Data("Gustine", "California", 95, 57, 11));
arr.push(new Data("Hacienda Heights", "California", 88, 69, 16));
arr.push(new Data("Half Moon Bay", "California", 73, 58, 24));
arr.push(new Data("Hamilton Branch", "California", 83, 41, 41));
arr.push(new Data("Hamilton City", "California", 94, 56, 25));
arr.push(new Data("Hanford", "California", 96, 54, 9));
arr.push(new Data("Happy Camp", "California", 90, 48, 43));
arr.push(new Data("Harbison Canyon", "California", 90, 69, 15));
arr.push(new Data("Hardwick", "California", 96, 54, 9));
arr.push(new Data("Hartley", "California", 94, 56, 26));
arr.push(new Data("Hasley Canyon", "California", 91, 64, 18));
arr.push(new Data("Hat Creek", "California", 87, 43, 42));
arr.push(new Data("Hawaiian Gardens", "California", 83, 67, 13));
arr.push(new Data("Hawthorne", "California", 77, 65, 14));
arr.push(new Data("Hayfork", "California", 92, 45, 46));
arr.push(new Data("Hayward", "California", 78, 58, 18));
arr.push(new Data("Healdsburg", "California", 87, 57, 42));
arr.push(new Data("Heber", "California", 106, 69, 3));
arr.push(new Data("Hemet", "California", 99, 67, 12));
arr.push(new Data("Herald", "California", 92, 55, 19));
arr.push(new Data("Hercules", "California", 78, 57, 24));
arr.push(new Data("Herlong", "California", 87, 42, 13));
arr.push(new Data("Hermosa Beach", "California", 77, 65, 14));
arr.push(new Data("Hesperia", "California", 97, 57, 15));
arr.push(new Data("Hickman", "California", 93, 55, 13));
arr.push(new Data("Hidden Hills", "California", 91, 67, 18));
arr.push(new Data("Hidden Meadows", "California", 88, 69, 14));
arr.push(new Data("Hidden Valley Lake", "California", 90, 55, 42));
arr.push(new Data("Highgrove", "California", 95, 68, 11));
arr.push(new Data("Highland", "California", 96, 67, 13));
arr.push(new Data("Highlands-Baywood Park", "California", 78, 58, 30));
arr.push(new Data("Hillsborough", "California", 73, 58, 23));
arr.push(new Data("Hilmar-Irwin", "California", 94, 56, 12));
arr.push(new Data("Hiouchi", "California", 64, 54, 71));
arr.push(new Data("Hollister", "California", 86, 59, 15));
arr.push(new Data("Holtville", "California", 106, 69, 3));
arr.push(new Data("Home Garden", "California", 96, 54, 9));
arr.push(new Data("Home Gardens", "California", 95, 67, 12));
arr.push(new Data("Homeland", "California", 99, 68, 12));
arr.push(new Data("Homestead Valley", "California", 99, 60, 8));
arr.push(new Data("Homewood Canyon", "California", 103, 59, 4));
arr.push(new Data("Honcut", "California", 94, 55, 34));
arr.push(new Data("Hood", "California", 92, 54, 19));
arr.push(new Data("Hopland", "California", 91, 56, 40));
arr.push(new Data("Hornbrook", "California", 90, 45, 21));
arr.push(new Data("Hughson", "California", 94, 56, 13));
arr.push(new Data("Humboldt Hill", "California", 66, 55, 46));
arr.push(new Data("Huntington Beach", "California", 80, 67, 12));
arr.push(new Data("Huntington Park", "California", 84, 68, 14));
arr.push(new Data("Huron", "California", 96, 56, 8));
arr.push(new Data("Hyampom", "California", 95, 49, 48));
arr.push(new Data("Hydesville", "California", 71, 53, 50));
arr.push(new Data("Idyllwild-Pine Cove", "California", 84, 52, 29));
arr.push(new Data("Imperial", "California", 106, 69, 3));
arr.push(new Data("Imperial Beach", "California", 77, 67, 10));
arr.push(new Data("Independence", "California", 98, 55, 6));
arr.push(new Data("Indian Wells", "California", 107, 69, 5));
arr.push(new Data("Indianola", "California", 66, 55, 46));
arr.push(new Data("Indio", "California", 107, 71, 3));
arr.push(new Data("Indio Hills", "California", 107, 67, 6));
arr.push(new Data("Industry", "California", 89, 69, 15));
arr.push(new Data("Inglewood", "California", 77, 65, 14));
arr.push(new Data("Interlaken", "California", 74, 61, 25));
arr.push(new Data("Inverness", "California", 81, 55, 42));
arr.push(new Data("Inyokern", "California", 100, 59, 6));
arr.push(new Data("Ione", "California", 94, 55, 21));
arr.push(new Data("Iron Horse", "California", 84, 42, 18));
arr.push(new Data("Irvine", "California", 83, 68, 13));
arr.push(new Data("Irwindale", "California", 89, 69, 16));
arr.push(new Data("Isla Vista", "California", 74, 63, 18));
arr.push(new Data("Isleton", "California", 91, 55, 17));
arr.push(new Data("Ivanhoe", "California", 95, 56, 13));
arr.push(new Data("Jackson", "California", 93, 54, 30));
arr.push(new Data("Jamestown", "California", 94, 56, 33));
arr.push(new Data("Jamul", "California", 89, 66, 16));
arr.push(new Data("Janesville", "California", 87, 41, 13));
arr.push(new Data("Jenner", "California", 77, 56, 52));
arr.push(new Data("Johnstonville", "California", 86, 41, 17));
arr.push(new Data("Joshua Tree", "California", 99, 61, 8));
arr.push(new Data("Julian", "California", 85, 52, 28));
arr.push(new Data("Junction City", "California", 94, 47, 36));
arr.push(new Data("June Lake", "California", 78, 41, 16));
arr.push(new Data("Jurupa Valley", "California", 95, 67, 11));
arr.push(new Data("Keddie", "California", 86, 45, 62));
arr.push(new Data("Keeler", "California", 98, 56, 6));
arr.push(new Data("Keene", "California", 94, 57, 12));
arr.push(new Data("Kelly Ridge", "California", 94, 55, 34));
arr.push(new Data("Kelseyville", "California", 89, 54, 41));
arr.push(new Data("Kennedy", "California", 92, 55, 17));
arr.push(new Data("Kennedy Meadows", "California", 100, 59, 6));
arr.push(new Data("Kensington", "California", 73, 58, 26));
arr.push(new Data("Kentfield", "California", 78, 56, 41));
arr.push(new Data("Kenwood", "California", 87, 58, 37));
arr.push(new Data("Kerman", "California", 96, 54, 12));
arr.push(new Data("Kernville", "California", 95, 58, 14));
arr.push(new Data("Keswick", "California", 96, 54, 34));
arr.push(new Data("Kettleman City", "California", 96, 56, 8));
arr.push(new Data("Keyes", "California", 94, 56, 13));
arr.push(new Data("King City", "California", 83, 62, 21));
arr.push(new Data("Kings Beach", "California", 78, 40, 28));
arr.push(new Data("Kingsburg", "California", 96, 55, 11));
arr.push(new Data("Kingvale", "California", 83, 41, 31));
arr.push(new Data("Kirkwood", "California", 87, 45, 18));
arr.push(new Data("Klamath", "California", 73, 51, 79));
arr.push(new Data("Knights Landing", "California", 93, 54, 21));
arr.push(new Data("Knightsen", "California", 90, 55, 15));
arr.push(new Data("La Canada Flintridge", "California", 88, 67, 22));
arr.push(new Data("La Crescenta-Montrose", "California", 88, 67, 22));
arr.push(new Data("La Habra", "California", 88, 69, 14));
arr.push(new Data("La Habra Heights", "California", 88, 69, 14));
arr.push(new Data("La Honda", "California", 81, 60, 36));
arr.push(new Data("La Mesa", "California", 86, 68, 12));
arr.push(new Data("La Mirada", "California", 86, 68, 15));
arr.push(new Data("La Palma", "California", 85, 68, 14));
arr.push(new Data("La Presa", "California", 85, 68, 13));
arr.push(new Data("La Puente", "California", 89, 70, 15));
arr.push(new Data("La Quinta", "California", 107, 71, 3));
arr.push(new Data("La Riviera", "California", 92, 54, 20));
arr.push(new Data("La Selva Beach", "California", 74, 61, 25));
arr.push(new Data("La Verne", "California", 93, 67, 19));
arr.push(new Data("La Vina", "California", 95, 54, 12));
arr.push(new Data("Ladera", "California", 78, 59, 31));
arr.push(new Data("Ladera Heights", "California", 77, 65, 14));
arr.push(new Data("Ladera Ranch", "California", 89, 67, 14));
arr.push(new Data("Lafayette", "California", 82, 57, 24));
arr.push(new Data("Laguna Beach", "California", 82, 66, 14));
arr.push(new Data("Laguna Hills", "California", 86, 66, 14));
arr.push(new Data("Laguna Niguel", "California", 85, 67, 14));
arr.push(new Data("Laguna Woods", "California", 88, 67, 14));
arr.push(new Data("Lagunitas-Forest Knolls", "California", 79, 56, 41));
arr.push(new Data("Lake Almanor Country Club", "California", 83, 41, 41));
arr.push(new Data("Lake Almanor Peninsula", "California", 83, 41, 41));
arr.push(new Data("Lake Almanor West", "California", 83, 41, 41));
arr.push(new Data("Lake Arrowhead", "California", 81, 45, 35));
arr.push(new Data("Lake California", "California", 96, 54, 34));
arr.push(new Data("Lake City", "California", 86, 40, 15));
arr.push(new Data("Lake Don Pedro", "California", 94, 56, 28));
arr.push(new Data("Lake Elsinore", "California", 98, 67, 12));
arr.push(new Data("Lake Forest", "California", 87, 66, 14));
arr.push(new Data("Lake Hughes", "California", 94, 55, 13));
arr.push(new Data("Lake Isabella", "California", 86, 51, 13));
arr.push(new Data("Lake Los Angeles", "California", 97, 57, 7));
arr.push(new Data("Lake Mathews", "California", 98, 68, 12));
arr.push(new Data("Lake Nacimiento", "California", 89, 60, 18));
arr.push(new Data("Lake of the Pines", "California", 92, 55, 41));
arr.push(new Data("Lake of the Woods", "California", 87, 52, 12));
arr.push(new Data("Lake Riverside", "California", 96, 63, 21));
arr.push(new Data("Lake San Marcos", "California", 82, 66, 13));
arr.push(new Data("Lake Sherwood", "California", 91, 67, 16));
arr.push(new Data("Lake Wildwood", "California", 91, 54, 41));
arr.push(new Data("Lakehead", "California", 95, 53, 60));
arr.push(new Data("Lakeland Village", "California", 97, 67, 12));
arr.push(new Data("Lakeport", "California", 89, 54, 43));
arr.push(new Data("Lakeside", "California", 90, 69, 14));
arr.push(new Data("Lakeview", "California", 99, 68, 12));
arr.push(new Data("Lakewood", "California", 83, 67, 14));
arr.push(new Data("Lamont", "California", 96, 57, 7));
arr.push(new Data("Lanare", "California", 95, 54, 9));
arr.push(new Data("Lancaster", "California", 98, 58, 8));
arr.push(new Data("Larkfield-Wikiup", "California", 84, 58, 37));
arr.push(new Data("Larkspur", "California", 78, 56, 41));
arr.push(new Data("Las Flores (Orange Cnty)", "California", 89, 67, 14));
arr.push(new Data("Las Flores (Tehama Cnty)", "California", 94, 55, 26));
arr.push(new Data("Las Lomas", "California", 74, 61, 25));
arr.push(new Data("Lathrop", "California", 92, 56, 15));
arr.push(new Data("Laton", "California", 95, 54, 9));
arr.push(new Data("Lawndale", "California", 77, 65, 14));
arr.push(new Data("Laytonville", "California", 87, 52, 52));
arr.push(new Data("Le Grand", "California", 94, 54, 13));
arr.push(new Data("Lebec", "California", 85, 50, 13));
arr.push(new Data("Lee Vining", "California", 79, 41, 15));
arr.push(new Data("Leggett", "California", 87, 52, 56));
arr.push(new Data("Lemon Cove", "California", 96, 57, 17));
arr.push(new Data("Lemon Grove", "California", 85, 68, 13));
arr.push(new Data("Lemon Hill", "California", 92, 54, 20));
arr.push(new Data("Lemoore", "California", 95, 54, 9));
arr.push(new Data("Lemoore Station", "California", 95, 54, 9));
arr.push(new Data("Lennox", "California", 77, 65, 14));
arr.push(new Data("Lenwood", "California", 100, 59, 5));
arr.push(new Data("Leona Valley", "California", 98, 58, 9));
arr.push(new Data("Lewiston", "California", 92, 45, 37));
arr.push(new Data("Lexington Hills", "California", 82, 54, 42));
arr.push(new Data("Lincoln", "California", 93, 54, 22));
arr.push(new Data("Lincoln Village", "California", 92, 55, 17));
arr.push(new Data("Linda", "California", 94, 55, 22));
arr.push(new Data("Lindcove", "California", 95, 56, 13));
arr.push(new Data("Linden", "California", 92, 55, 17));
arr.push(new Data("Lindsay", "California", 96, 57, 12));
arr.push(new Data("Linnell Camp", "California", 95, 56, 13));
arr.push(new Data("Litchfield", "California", 85, 41, 16));
arr.push(new Data("Littlerock", "California", 97, 58, 8));
arr.push(new Data("Live Oak", "California", 94, 54, 25));
arr.push(new Data("Live Oak CDP", "California", 75, 61, 27));
arr.push(new Data("Livermore", "California", 89, 56, 18));
arr.push(new Data("Livingston", "California", 93, 54, 12));
arr.push(new Data("Lockeford", "California", 92, 55, 19));
arr.push(new Data("Lockwood", "California", 86, 60, 18));
arr.push(new Data("Lodi", "California", 92, 55, 19));
arr.push(new Data("Lodoga", "California", 93, 56, 23));
arr.push(new Data("Loleta", "California", 67, 55, 46));
arr.push(new Data("Loma Linda", "California", 96, 67, 13));
arr.push(new Data("Loma Mar", "California", 80, 59, 28));
arr.push(new Data("Loma Rica", "California", 94, 55, 23));
arr.push(new Data("Lomita", "California", 77, 65, 14));
arr.push(new Data("Lompico", "California", 82, 60, 36));
arr.push(new Data("Lompoc", "California", 75, 64, 16));
arr.push(new Data("London", "California", 94, 54, 10));
arr.push(new Data("Lone Pine", "California", 98, 56, 6));
arr.push(new Data("Long Barn", "California", 84, 46, 46));
arr.push(new Data("Long Beach", "California", 81, 66, 14));
arr.push(new Data("Loomis", "California", 93, 55, 21));
arr.push(new Data("Los Alamitos", "California", 83, 67, 13));
arr.push(new Data("Los Alamos", "California", 76, 64, 17));
arr.push(new Data("Los Altos", "California", 81, 59, 19));
arr.push(new Data("Los Altos Hills", "California", 81, 59, 20));
arr.push(new Data("Los Angeles", "California", 85, 67, 16));
arr.push(new Data("Los Banos", "California", 94, 55, 10));
arr.push(new Data("Los Berros", "California", 74, 62, 20));
arr.push(new Data("Los Gatos", "California", 84, 59, 31));
arr.push(new Data("Los Molinos", "California", 94, 55, 26));
arr.push(new Data("Los Olivos", "California", 86, 66, 21));
arr.push(new Data("Los Osos", "California", 72, 63, 18));
arr.push(new Data("Los Ranchos", "California", 75, 62, 20));
arr.push(new Data("Lost Hills", "California", 97, 57, 7));
arr.push(new Data("Lower Lake", "California", 89, 54, 38));
arr.push(new Data("Loyalton", "California", 85, 43, 16));
arr.push(new Data("Loyola", "California", 80, 58, 18));
arr.push(new Data("Lucas Valley-Marinwood", "California", 78, 56, 41));
arr.push(new Data("Lucerne", "California", 92, 55, 26));
arr.push(new Data("Lucerne Valley", "California", 98, 59, 14));
arr.push(new Data("Lynwood", "California", 79, 66, 14));
arr.push(new Data("Lytle Creek", "California", 90, 51, 31));
arr.push(new Data("Macdoel", "California", 86, 40, 18));
arr.push(new Data("Mad River", "California", 73, 48, 70));
arr.push(new Data("Madera", "California", 96, 55, 13));
arr.push(new Data("Madera Acres", "California", 96, 55, 13));
arr.push(new Data("Madison", "California", 95, 56, 24));
arr.push(new Data("Magalia", "California", 90, 52, 65));
arr.push(new Data("Malaga", "California", 96, 55, 12));
arr.push(new Data("Malibu", "California", 87, 67, 20));
arr.push(new Data("Mammoth Lakes", "California", 77, 41, 15));
arr.push(new Data("Manchester", "California", 81, 55, 42));
arr.push(new Data("Manhattan Beach", "California", 77, 65, 14));
arr.push(new Data("Manila", "California", 66, 55, 46));
arr.push(new Data("Manteca", "California", 92, 56, 15));
arr.push(new Data("Manton", "California", 90, 48, 48));
arr.push(new Data("March ARB", "California", 98, 67, 12));
arr.push(new Data("Maricopa", "California", 96, 56, 7));
arr.push(new Data("Marin City", "California", 77, 55, 33));
arr.push(new Data("Marina", "California", 70, 60, 17));
arr.push(new Data("Marina del Rey", "California", 75, 64, 13));
arr.push(new Data("Mariposa", "California", 92, 55, 31));
arr.push(new Data("Markleeville", "California", 76, 39, 33));
arr.push(new Data("Martell", "California", 93, 54, 30));
arr.push(new Data("Martinez", "California", 88, 56, 18));
arr.push(new Data("Marysville", "California", 94, 55, 22));
arr.push(new Data("Matheny", "California", 95, 55, 10));
arr.push(new Data("Mather", "California", 92, 54, 20));
arr.push(new Data("Maxwell", "California", 94, 56, 25));
arr.push(new Data("Mayfair", "California", 98, 56, 13));
arr.push(new Data("Mayflower Village", "California", 88, 68, 18));
arr.push(new Data("Maywood", "California", 84, 68, 15));
arr.push(new Data("McArthur", "California", 86, 43, 26));
arr.push(new Data("McClellan Park", "California", 92, 54, 20));
arr.push(new Data("McClenney Tract", "California", 94, 57, 15));
arr.push(new Data("McCloud", "California", 87, 46, 42));
arr.push(new Data("McFarland", "California", 97, 57, 7));
arr.push(new Data("McGee Creek", "California", 77, 41, 15));
arr.push(new Data("McKinleyville", "California", 65, 54, 50));
arr.push(new Data("McKittrick", "California", 96, 56, 7));
arr.push(new Data("McSwain", "California", 93, 54, 13));
arr.push(new Data("Mead Valley", "California", 99, 68, 12));
arr.push(new Data("Meadow Valley", "California", 86, 45, 64));
arr.push(new Data("Meadow Vista", "California", 90, 53, 39));
arr.push(new Data("Meadowbrook", "California", 99, 68, 12));
arr.push(new Data("Mecca", "California", 107, 71, 3));
arr.push(new Data("Meiners Oaks", "California", 87, 67, 19));
arr.push(new Data("Mendocino", "California", 78, 53, 41));
arr.push(new Data("Mendota", "California", 95, 55, 11));
arr.push(new Data("Menifee", "California", 99, 67, 12));
arr.push(new Data("Menlo Park", "California", 79, 58, 17));
arr.push(new Data("Mentone", "California", 97, 67, 13));
arr.push(new Data("Merced", "California", 94, 54, 13));
arr.push(new Data("Meridian", "California", 94, 55, 24));
arr.push(new Data("Mesa", "California", 94, 50, 5));
arr.push(new Data("Mesa Verde", "California", 107, 66, 4));
arr.push(new Data("Mesa Vista", "California", 76, 39, 33));
arr.push(new Data("Mettler", "California", 96, 57, 7));
arr.push(new Data("Mexican Colony", "California", 97, 57, 7));
arr.push(new Data("Middletown", "California", 88, 54, 39));
arr.push(new Data("Midpines", "California", 92, 54, 33));
arr.push(new Data("Midway City", "California", 84, 68, 13));
arr.push(new Data("Milford", "California", 86, 42, 17));
arr.push(new Data("Mill Valley", "California", 77, 55, 41));
arr.push(new Data("Millbrae", "California", 71, 57, 25));
arr.push(new Data("Millville", "California", 96, 54, 34));
arr.push(new Data("Milpitas", "California", 80, 58, 16));
arr.push(new Data("Mineral", "California", 80, 41, 47));
arr.push(new Data("Minkler", "California", 98, 56, 15));
arr.push(new Data("Mira Monte", "California", 86, 67, 19));
arr.push(new Data("Miranda", "California", 77, 51, 63));
arr.push(new Data("Mission Canyon", "California", 74, 63, 20));
arr.push(new Data("Mission Hills", "California", 75, 64, 16));
arr.push(new Data("Mission Viejo", "California", 88, 67, 14));
arr.push(new Data("Mi-Wuk Village", "California", 84, 45, 49));
arr.push(new Data("Modesto", "California", 92, 55, 13));
arr.push(new Data("Mohawk Vista", "California", 85, 43, 38));
arr.push(new Data("Mojave", "California", 97, 57, 7));
arr.push(new Data("Mokelumne Hill", "California", 91, 51, 43));
arr.push(new Data("Monmouth", "California", 96, 55, 12));
arr.push(new Data("Mono City", "California", 79, 41, 15));
arr.push(new Data("Mono Vista", "California", 90, 52, 41));
arr.push(new Data("Monrovia", "California", 89, 68, 20));
arr.push(new Data("Monson", "California", 94, 54, 10));
arr.push(new Data("Montague", "California", 90, 45, 20));
arr.push(new Data("Montalvin Manor", "California", 78, 56, 36));
arr.push(new Data("Montara", "California", 70, 58, 27));
arr.push(new Data("Montclair", "California", 93, 67, 17));
arr.push(new Data("Monte Rio", "California", 82, 56, 45));
arr.push(new Data("Monte Sereno", "California", 86, 59, 34));
arr.push(new Data("Montebello", "California", 87, 69, 15));
arr.push(new Data("Montecito", "California", 74, 63, 18));
arr.push(new Data("Monterey", "California", 68, 59, 18));
arr.push(new Data("Monterey Park", "California", 87, 69, 16));
arr.push(new Data("Monterey Park Tract", "California", 94, 56, 13));
arr.push(new Data("Montgomery Creek", "California", 91, 48, 47));
arr.push(new Data("Monument Hills", "California", 93, 54, 21));
arr.push(new Data("Moorpark", "California", 88, 68, 18));
arr.push(new Data("Morada", "California", 92, 55, 17));
arr.push(new Data("Moraga", "California", 83, 57, 24));
arr.push(new Data("Moreno Valley", "California", 98, 67, 12));
arr.push(new Data("Morgan Hill", "California", 86, 59, 21));
arr.push(new Data("Morongo Valley", "California", 98, 61, 12));
arr.push(new Data("Morro Bay", "California", 71, 62, 19));
arr.push(new Data("Moskowite Corner", "California", 83, 57, 27));
arr.push(new Data("Moss Beach", "California", 70, 58, 27));
arr.push(new Data("Moss Landing", "California", 73, 61, 20));
arr.push(new Data("Mount Hebron", "California", 86, 40, 18));
arr.push(new Data("Mount Hermon", "California", 82, 60, 36));
arr.push(new Data("Mount Shasta", "California", 86, 45, 41));
arr.push(new Data("Mountain Center", "California", 84, 53, 28));
arr.push(new Data("Mountain Gate", "California", 96, 54, 44));
arr.push(new Data("Mountain House", "California", 91, 56, 13));
arr.push(new Data("Mountain Mesa", "California", 86, 51, 13));
arr.push(new Data("Mountain Ranch", "California", 91, 51, 43));
arr.push(new Data("Mountain View", "California", 79, 58, 16));
arr.push(new Data("Mountain View Acres", "California", 97, 57, 14));
arr.push(new Data("Mountain View CDP", "California", 88, 56, 18));
arr.push(new Data("Muir Beach", "California", 77, 55, 33));
arr.push(new Data("Murphys", "California", 90, 51, 44));
arr.push(new Data("Murrieta", "California", 96, 67, 12));
arr.push(new Data("Muscoy", "California", 96, 67, 14));
arr.push(new Data("Myrtletown", "California", 66, 55, 46));
arr.push(new Data("Napa", "California", 83, 57, 27));
arr.push(new Data("National City", "California", 78, 67, 10));
arr.push(new Data("Needles", "California", 108, 64, 6));
arr.push(new Data("Nevada City", "California", 87, 50, 58));
arr.push(new Data("New Cuyama", "California", 94, 61, 18));
arr.push(new Data("New Pine Creek", "California", 83, 40, 15));
arr.push(new Data("Newcastle", "California", 92, 55, 32));
arr.push(new Data("Newell", "California", 85, 40, 13));
arr.push(new Data("Newman", "California", 94, 56, 12));
arr.push(new Data("Newport Beach", "California", 80, 66, 12));
arr.push(new Data("Nicasio", "California", 81, 55, 41));
arr.push(new Data("Nice", "California", 89, 54, 28));
arr.push(new Data("Nicolaus", "California", 94, 54, 21));
arr.push(new Data("Niland", "California", 107, 70, 3));
arr.push(new Data("Nipinnawasee", "California", 93, 55, 31));
arr.push(new Data("Nipomo", "California", 78, 64, 17));
arr.push(new Data("Norco", "California", 95, 67, 12));
arr.push(new Data("Nord", "California", 93, 55, 27));
arr.push(new Data("Norris Canyon", "California", 84, 57, 19));
arr.push(new Data("North Auburn", "California", 92, 55, 39));
arr.push(new Data("North Edwards", "California", 98, 58, 7));
arr.push(new Data("North El Monte", "California", 87, 69, 17));
arr.push(new Data("North Fair Oaks", "California", 80, 58, 17));
arr.push(new Data("North Gate", "California", 88, 56, 18));
arr.push(new Data("North Highlands", "California", 92, 54, 20));
arr.push(new Data("North Lakeport", "California", 89, 54, 43));
arr.push(new Data("North Richmond", "California", 75, 57, 28));
arr.push(new Data("North San Juan", "California", 87, 49, 58));
arr.push(new Data("North Shore", "California", 107, 71, 3));
arr.push(new Data("North Tustin", "California", 85, 68, 13));
arr.push(new Data("Norwalk", "California", 86, 68, 14));
arr.push(new Data("Novato", "California", 81, 55, 38));
arr.push(new Data("Nuevo", "California", 99, 68, 12));
arr.push(new Data("Oak Glen", "California", 98, 63, 23));
arr.push(new Data("Oak Hills", "California", 97, 57, 15));
arr.push(new Data("Oak Park", "California", 87, 66, 17));
arr.push(new Data("Oak Shores", "California", 88, 60, 19));
arr.push(new Data("Oak View", "California", 83, 67, 19));
arr.push(new Data("Oakdale", "California", 93, 55, 13));
arr.push(new Data("Oakhurst", "California", 94, 55, 29));
arr.push(new Data("Oakland", "California", 73, 58, 24));
arr.push(new Data("Oakley", "California", 90, 55, 14));
arr.push(new Data("Oasis", "California", 107, 71, 3));
arr.push(new Data("Occidental", "California", 80, 57, 45));
arr.push(new Data("Oceano", "California", 74, 62, 19));
arr.push(new Data("Oceanside", "California", 77, 65, 13));
arr.push(new Data("Ocotillo", "California", 106, 69, 4));
arr.push(new Data("Oildale", "California", 96, 57, 7));
arr.push(new Data("Ojai", "California", 87, 67, 19));
arr.push(new Data("Olancha", "California", 99, 56, 7));
arr.push(new Data("Old Fig Garden", "California", 96, 55, 12));
arr.push(new Data("Old Station", "California", 83, 41, 44));
arr.push(new Data("Olivehurst", "California", 94, 55, 22));
arr.push(new Data("Ontario", "California", 93, 67, 16));
arr.push(new Data("Onyx", "California", 95, 58, 13));
arr.push(new Data("Orange", "California", 87, 69, 14));
arr.push(new Data("Orange Cove", "California", 95, 56, 16));
arr.push(new Data("Orangevale", "California", 93, 55, 21));
arr.push(new Data("Orcutt", "California", 76, 64, 16));
arr.push(new Data("Orick", "California", 73, 51, 58));
arr.push(new Data("Orinda", "California", 78, 58, 26));
arr.push(new Data("Orland", "California", 94, 56, 24));
arr.push(new Data("Orosi", "California", 95, 56, 15));
arr.push(new Data("Oroville", "California", 94, 55, 34));
arr.push(new Data("Oroville East", "California", 94, 55, 34));
arr.push(new Data("Oxnard", "California", 74, 65, 15));
arr.push(new Data("Pacheco", "California", 88, 56, 18));
arr.push(new Data("Pacific Grove", "California", 68, 59, 18));
arr.push(new Data("Pacifica", "California", 71, 57, 25));
arr.push(new Data("Pajaro", "California", 74, 61, 25));
arr.push(new Data("Pajaro Dunes", "California", 74, 61, 25));
arr.push(new Data("Palermo", "California", 94, 55, 33));
arr.push(new Data("Palm Desert", "California", 107, 69, 5));
arr.push(new Data("Palm Springs", "California", 107, 69, 5));
arr.push(new Data("Palmdale", "California", 97, 58, 9));
arr.push(new Data("Palo Alto", "California", 80, 58, 17));
arr.push(new Data("Palo Cedro", "California", 96, 54, 34));
arr.push(new Data("Palo Verde", "California", 107, 66, 4));
arr.push(new Data("Palos Verdes Estates", "California", 77, 66, 15));
arr.push(new Data("Panorama Heights", "California", 94, 57, 15));
arr.push(new Data("Paradise", "California", 91, 53, 64));
arr.push(new Data("Paradise CDP", "California", 94, 50, 5));
arr.push(new Data("Paradise Park", "California", 79, 61, 34));
arr.push(new Data("Paramount", "California", 83, 67, 14));
arr.push(new Data("Parklawn", "California", 93, 55, 13));
arr.push(new Data("Parksdale", "California", 96, 55, 13));
arr.push(new Data("Parkway", "California", 92, 54, 20));
arr.push(new Data("Parkwood", "California", 95, 54, 12));
arr.push(new Data("Parlier", "California", 96, 55, 12));
arr.push(new Data("Pasadena", "California", 89, 67, 21));
arr.push(new Data("Pasatiempo", "California", 79, 61, 34));
arr.push(new Data("Paskenta", "California", 94, 56, 24));
arr.push(new Data("Paso Robles", "California", 89, 60, 18));
arr.push(new Data("Patterson", "California", 94, 56, 12));
arr.push(new Data("Patterson Tract", "California", 94, 54, 10));
arr.push(new Data("Patton Village", "California", 87, 42, 13));
arr.push(new Data("Paynes Creek", "California", 93, 53, 38));
arr.push(new Data("Pearsonville", "California", 100, 59, 6));
arr.push(new Data("Penn Valley", "California", 91, 54, 41));
arr.push(new Data("Penngrove", "California", 84, 57, 30));
arr.push(new Data("Penryn", "California", 93, 55, 31));
arr.push(new Data("Perris", "California", 99, 67, 12));
arr.push(new Data("Pescadero", "California", 75, 59, 30));
arr.push(new Data("Petaluma", "California", 84, 57, 30));
arr.push(new Data("Peters", "California", 92, 55, 17));
arr.push(new Data("Phelan", "California", 97, 57, 6));
arr.push(new Data("Phillipsville", "California", 87, 51, 63));
arr.push(new Data("Philo", "California", 91, 56, 40));
arr.push(new Data("Phoenix Lake", "California", 90, 52, 41));
arr.push(new Data("Pico Rivera", "California", 87, 69, 15));
arr.push(new Data("Piedmont", "California", 73, 58, 25));
arr.push(new Data("Pike", "California", 87, 49, 58));
arr.push(new Data("Pine Canyon", "California", 83, 62, 21));
arr.push(new Data("Pine Flat", "California", 97, 58, 10));
arr.push(new Data("Pine Grove", "California", 92, 51, 42));
arr.push(new Data("Pine Hills", "California", 66, 55, 46));
arr.push(new Data("Pine Mountain Club", "California", 88, 53, 12));
arr.push(new Data("Pine Mountain Lake", "California", 90, 52, 40));
arr.push(new Data("Pine Valley", "California", 86, 53, 21));
arr.push(new Data("Pinole", "California", 80, 56, 27));
arr.push(new Data("Pioneer", "California", 91, 52, 48));
arr.push(new Data("Piru", "California", 92, 67, 18));
arr.push(new Data("Pismo Beach", "California", 74, 62, 20));
arr.push(new Data("Pittsburg", "California", 88, 56, 16));
arr.push(new Data("Pixley", "California", 97, 57, 9));
arr.push(new Data("Placentia", "California", 88, 69, 14));
arr.push(new Data("Placerville", "California", 92, 53, 39));
arr.push(new Data("Plainview", "California", 96, 57, 12));
arr.push(new Data("Planada", "California", 94, 54, 13));
arr.push(new Data("Pleasant Hill", "California", 88, 56, 18));
arr.push(new Data("Pleasanton", "California", 85, 57, 19));
arr.push(new Data("Pleasure Point", "California", 74, 61, 25));
arr.push(new Data("Plumas Eureka", "California", 85, 43, 38));
arr.push(new Data("Plumas Lake", "California", 94, 55, 22));
arr.push(new Data("Plymouth", "California", 93, 54, 30));
arr.push(new Data("Point Arena", "California", 91, 56, 40));
arr.push(new Data("Point Reyes Station", "California", 81, 55, 37));
arr.push(new Data("Pollock Pines", "California", 91, 52, 52));
arr.push(new Data("Pomona", "California", 93, 66, 17));
arr.push(new Data("Poplar-Cotton Center", "California", 97, 58, 13));
arr.push(new Data("Port Costa", "California", 88, 56, 18));
arr.push(new Data("Port Hueneme", "California", 73, 65, 14));
arr.push(new Data("Porterville", "California", 97, 58, 13));
arr.push(new Data("Portola", "California", 84, 42, 18));
arr.push(new Data("Portola Valley", "California", 78, 59, 31));
arr.push(new Data("Posey", "California", 94, 57, 15));
arr.push(new Data("Potrero", "California", 93, 63, 20));
arr.push(new Data("Potter Valley", "California", 89, 54, 46));
arr.push(new Data("Poway", "California", 89, 68, 13));
arr.push(new Data("Prattville", "California", 83, 41, 40));
arr.push(new Data("Princeton", "California", 93, 56, 25));
arr.push(new Data("Proberta", "California", 94, 55, 26));
arr.push(new Data("Prunedale", "California", 73, 61, 18));
arr.push(new Data("Quartz Hill", "California", 98, 58, 8));
arr.push(new Data("Quincy", "California", 86, 45, 62));
arr.push(new Data("Rackerby", "California", 92, 55, 41));
arr.push(new Data("Rail Road Flat", "California", 91, 51, 43));
arr.push(new Data("Rainbow", "California", 87, 67, 14));
arr.push(new Data("Raisin City", "California", 97, 56, 12));
arr.push(new Data("Ramona", "California", 90, 65, 16));
arr.push(new Data("Rancho Calaveras", "California", 95, 56, 28));
arr.push(new Data("Rancho Cordova", "California", 92, 54, 20));
arr.push(new Data("Rancho Cucamonga", "California", 94, 67, 19));
arr.push(new Data("Rancho Mirage", "California", 107, 69, 5));
arr.push(new Data("Rancho Murieta", "California", 93, 55, 21));
arr.push(new Data("Rancho Palos Verdes", "California", 84, 66, 15));
arr.push(new Data("Rancho San Diego", "California", 90, 69, 15));
arr.push(new Data("Rancho Santa Fe", "California", 83, 67, 12));
arr.push(new Data("Rancho Santa Margarita", "California", 90, 67, 14));
arr.push(new Data("Rancho Tehama Reserve", "California", 94, 55, 25));
arr.push(new Data("Randsburg", "California", 97, 55, 7));
arr.push(new Data("Red Bluff", "California", 95, 55, 28));
arr.push(new Data("Red Corral", "California", 91, 51, 45));
arr.push(new Data("Redcrest", "California", 71, 53, 55));
arr.push(new Data("Redding", "California", 96, 54, 38));
arr.push(new Data("Redlands", "California", 98, 67, 14));
arr.push(new Data("Redondo Beach", "California", 77, 66, 14));
arr.push(new Data("Redway", "California", 87, 51, 63));
arr.push(new Data("Redwood City", "California", 81, 58, 23));
arr.push(new Data("Redwood Valley", "California", 91, 55, 41));
arr.push(new Data("Reedley", "California", 96, 55, 12));
arr.push(new Data("Reliez Valley", "California", 83, 57, 24));
arr.push(new Data("Rialto", "California", 96, 67, 14));
arr.push(new Data("Richfield", "California", 94, 55, 25));
arr.push(new Data("Richgrove", "California", 98, 58, 9));
arr.push(new Data("Richmond", "California", 75, 57, 28));
arr.push(new Data("Richvale", "California", 94, 55, 34));
arr.push(new Data("Ridgecrest", "California", 102, 59, 5));
arr.push(new Data("Ridgemark", "California", 86, 59, 15));
arr.push(new Data("Rio del Mar", "California", 74, 61, 25));
arr.push(new Data("Rio Dell", "California", 71, 53, 50));
arr.push(new Data("Rio Linda", "California", 92, 54, 20));
arr.push(new Data("Rio Oso", "California", 94, 54, 21));
arr.push(new Data("Rio Vista", "California", 91, 55, 20));
arr.push(new Data("Ripley", "California", 107, 66, 4));
arr.push(new Data("Ripon", "California", 93, 55, 13));
arr.push(new Data("River Pines", "California", 92, 52, 42));
arr.push(new Data("Riverbank", "California", 93, 55, 13));
arr.push(new Data("Riverdale", "California", 95, 54, 9));
arr.push(new Data("Riverdale Park", "California", 93, 55, 13));
arr.push(new Data("Riverside", "California", 95, 68, 11));
arr.push(new Data("Robbins", "California", 93, 54, 21));
arr.push(new Data("Rocklin", "California", 93, 54, 21));
arr.push(new Data("Rodeo", "California", 83, 57, 21));
arr.push(new Data("Rodriguez Camp", "California", 98, 58, 9));
arr.push(new Data("Rohnert Park", "California", 83, 58, 32));
arr.push(new Data("Rolling Hills", "California", 77, 66, 15));
arr.push(new Data("Rolling Hills CDP", "California", 96, 55, 13));
arr.push(new Data("Rolling Hills Estates", "California", 77, 66, 15));
arr.push(new Data("Rollingwood", "California", 78, 56, 36));
arr.push(new Data("Romoland", "California", 99, 67, 12));
arr.push(new Data("Rosamond", "California", 97, 58, 8));
arr.push(new Data("Rose Hills", "California", 89, 69, 16));
arr.push(new Data("Rosedale", "California", 96, 57, 7));
arr.push(new Data("Roseland", "California", 83, 58, 37));
arr.push(new Data("Rosemead", "California", 87, 69, 16));
arr.push(new Data("Rosemont", "California", 92, 54, 20));
arr.push(new Data("Roseville", "California", 93, 54, 21));
arr.push(new Data("Ross", "California", 79, 56, 41));
arr.push(new Data("Rossmoor", "California", 83, 67, 13));
arr.push(new Data("Rough and Ready", "California", 89, 52, 51));
arr.push(new Data("Round Mountain", "California", 95, 52, 66));
arr.push(new Data("Round Valley", "California", 94, 50, 5));
arr.push(new Data("Rouse", "California", 93, 55, 13));
arr.push(new Data("Rowland Heights", "California", 88, 69, 16));
arr.push(new Data("Running Springs", "California", 82, 47, 35));
arr.push(new Data("Ruth", "California", 73, 48, 70));
arr.push(new Data("Rutherford", "California", 87, 58, 34));
arr.push(new Data("Sacramento", "California", 92, 54, 20));
arr.push(new Data("Salida", "California", 93, 55, 13));
arr.push(new Data("Salinas", "California", 71, 61, 15));
arr.push(new Data("Salmon Creek", "California", 71, 57, 40));
arr.push(new Data("Salton City", "California", 107, 70, 3));
arr.push(new Data("Salton Sea Beach", "California", 107, 71, 3));
arr.push(new Data("Samoa", "California", 66, 55, 46));
arr.push(new Data("San Andreas", "California", 94, 56, 32));
arr.push(new Data("San Anselmo", "California", 79, 55, 41));
arr.push(new Data("San Antonio Heights", "California", 93, 67, 22));
arr.push(new Data("San Ardo", "California", 90, 61, 13));
arr.push(new Data("San Bernardino", "California", 96, 67, 13));
arr.push(new Data("San Bruno", "California", 71, 57, 26));
arr.push(new Data("San Carlos", "California", 80, 59, 27));
arr.push(new Data("San Clemente", "California", 86, 67, 14));
arr.push(new Data("San Diego", "California", 80, 66, 12));
arr.push(new Data("San Diego Country Estates", "California", 90, 65, 16));
arr.push(new Data("San Dimas", "California", 92, 67, 19));
arr.push(new Data("San Fernando", "California", 89, 66, 17));
arr.push(new Data("San Francisco", "California", 69, 58, 25));
arr.push(new Data("San Gabriel", "California", 88, 69, 16));
arr.push(new Data("San Geronimo", "California", 79, 56, 41));
arr.push(new Data("San Jacinto", "California", 99, 67, 12));
arr.push(new Data("San Joaquin", "California", 95, 55, 9));
arr.push(new Data("San Jose", "California", 82, 58, 17));
arr.push(new Data("San Juan Bautista", "California", 82, 60, 18));
arr.push(new Data("San Juan Capistrano", "California", 86, 67, 14));
arr.push(new Data("San Leandro", "California", 74, 57, 21));
arr.push(new Data("San Lorenzo", "California", 74, 57, 21));
arr.push(new Data("San Lucas", "California", 86, 61, 18));
arr.push(new Data("San Luis Obispo", "California", 75, 62, 20));
arr.push(new Data("San Marcos", "California", 82, 66, 14));
arr.push(new Data("San Marino", "California", 89, 68, 19));
arr.push(new Data("San Martin", "California", 84, 60, 19));
arr.push(new Data("San Mateo", "California", 75, 58, 24));
arr.push(new Data("San Miguel (Contra Costa Cnty)", "California", 83, 57, 20));
arr.push(new Data("San Miguel (San Luis Obispo Cnty)", "California", 88, 60, 17));
arr.push(new Data("San Pablo", "California", 78, 56, 36));
arr.push(new Data("San Pasqual", "California", 89, 67, 21));
arr.push(new Data("San Rafael", "California", 78, 56, 41));
arr.push(new Data("San Ramon", "California", 84, 57, 19));
arr.push(new Data("San Simeon", "California", 74, 63, 20));
arr.push(new Data("Sand City", "California", 69, 60, 17));
arr.push(new Data("Sanger", "California", 98, 56, 15));
arr.push(new Data("Santa Ana", "California", 84, 68, 13));
arr.push(new Data("Santa Barbara", "California", 74, 63, 19));
arr.push(new Data("Santa Clara", "California", 80, 58, 15));
arr.push(new Data("Santa Clarita", "California", 91, 64, 18));
arr.push(new Data("Santa Cruz", "California", 78, 61, 33));
arr.push(new Data("Santa Fe Springs", "California", 86, 69, 15));
arr.push(new Data("Santa Margarita", "California", 87, 60, 28));
arr.push(new Data("Santa Monica", "California", 74, 64, 14));
arr.push(new Data("Santa Nella", "California", 95, 57, 11));
arr.push(new Data("Santa Paula", "California", 79, 67, 16));
arr.push(new Data("Santa Rosa", "California", 84, 58, 38));
arr.push(new Data("Santa Rosa Valley", "California", 79, 67, 16));
arr.push(new Data("Santa Susana", "California", 95, 68, 17));
arr.push(new Data("Santa Venetia", "California", 78, 56, 41));
arr.push(new Data("Santa Ynez", "California", 84, 65, 21));
arr.push(new Data("Santee", "California", 85, 68, 13));
arr.push(new Data("Saranap", "California", 83, 57, 23));
arr.push(new Data("Saratoga", "California", 86, 59, 34));
arr.push(new Data("Saticoy", "California", 79, 67, 16));
arr.push(new Data("Sausalito", "California", 77, 55, 33));
arr.push(new Data("Scotia", "California", 75, 52, 56));
arr.push(new Data("Scotts Valley", "California", 82, 60, 36));
arr.push(new Data("Sea Ranch", "California", 82, 57, 43));
arr.push(new Data("Seacliff", "California", 74, 61, 25));
arr.push(new Data("Seal Beach", "California", 83, 67, 13));
arr.push(new Data("Searles Valley", "California", 103, 59, 4));
arr.push(new Data("Seaside", "California", 69, 60, 17));
arr.push(new Data("Sebastopol", "California", 83, 58, 37));
arr.push(new Data("Seeley", "California", 106, 69, 3));
arr.push(new Data("Selma", "California", 96, 55, 12));
arr.push(new Data("Sereno del Mar", "California", 71, 57, 40));
arr.push(new Data("Seville", "California", 95, 56, 13));
arr.push(new Data("Shafter", "California", 97, 57, 7));
arr.push(new Data("Shandon", "California", 90, 60, 23));
arr.push(new Data("Shasta", "California", 96, 53, 43));
arr.push(new Data("Shasta Lake", "California", 96, 53, 47));
arr.push(new Data("Shaver Lake", "California", 82, 49, 36));
arr.push(new Data("Shell Ridge", "California", 88, 56, 18));
arr.push(new Data("Shelter Cove", "California", 81, 52, 70));
arr.push(new Data("Sheridan", "California", 94, 54, 21));
arr.push(new Data("Shingle Springs", "California", 92, 54, 37));
arr.push(new Data("Shingletown", "California", 89, 44, 45));
arr.push(new Data("Shoshone", "California", 104, 60, 5));
arr.push(new Data("Sierra Brooks", "California", 85, 43, 16));
arr.push(new Data("Sierra City", "California", 82, 44, 70));
arr.push(new Data("Sierra Madre", "California", 90, 67, 22));
arr.push(new Data("Sierra Village", "California", 84, 45, 48));
arr.push(new Data("Sierraville", "California", 79, 39, 35));
arr.push(new Data("Signal Hill", "California", 82, 67, 14));
arr.push(new Data("Silver Lakes", "California", 98, 58, 6));
arr.push(new Data("Silverado Resort", "California", 83, 57, 27));
arr.push(new Data("Simi Valley", "California", 94, 68, 17));
arr.push(new Data("Sisquoc", "California", 78, 64, 16));
arr.push(new Data("Sky Valley", "California", 107, 67, 6));
arr.push(new Data("Sleepy Hollow", "California", 79, 55, 41));
arr.push(new Data("Smartsville", "California", 92, 55, 38));
arr.push(new Data("Smith Corner", "California", 97, 57, 7));
arr.push(new Data("Smith River", "California", 68, 54, 78));
arr.push(new Data("Snelling", "California", 93, 54, 16));
arr.push(new Data("Soda Bay", "California", 89, 54, 41));
arr.push(new Data("Soda Springs", "California", 79, 39, 35));
arr.push(new Data("Solana Beach", "California", 75, 64, 13));
arr.push(new Data("Soledad", "California", 78, 61, 23));
arr.push(new Data("Solvang", "California", 84, 65, 19));
arr.push(new Data("Sonoma", "California", 85, 57, 31));
arr.push(new Data("Sonora", "California", 90, 52, 41));
arr.push(new Data("Soquel", "California", 74, 61, 25));
arr.push(new Data("Soulsbyville", "California", 89, 52, 40));
arr.push(new Data("South Dos Palos", "California", 94, 55, 12));
arr.push(new Data("South El Monte", "California", 87, 69, 16));
arr.push(new Data("South Gate", "California", 79, 66, 14));
arr.push(new Data("South Lake Tahoe", "California", 79, 43, 23));
arr.push(new Data("South Monrovia Island", "California", 89, 68, 18));
arr.push(new Data("South Oroville", "California", 94, 55, 34));
arr.push(new Data("South Pasadena", "California", 89, 67, 19));
arr.push(new Data("South San Francisco", "California", 68, 57, 22));
arr.push(new Data("South San Gabriel", "California", 87, 69, 16));
arr.push(new Data("South San Jose Hills", "California", 89, 70, 15));
arr.push(new Data("South Taft", "California", 96, 56, 6));
arr.push(new Data("South Whittier", "California", 87, 69, 15));
arr.push(new Data("Spaulding", "California", 86, 41, 17));
arr.push(new Data("Spreckels", "California", 71, 61, 15));
arr.push(new Data("Spring Valley (Lake Cnty)", "California", 90, 55, 32));
arr.push(new Data("Spring Valley (San Diego Cnty)", "California", 85, 68, 13));
arr.push(new Data("Spring Valley Lake", "California", 97, 57, 14));
arr.push(new Data("Springville", "California", 97, 58, 23));
arr.push(new Data("Squaw Valley", "California", 96, 55, 29));
arr.push(new Data("Squirrel Mountain Valley", "California", 86, 51, 13));
arr.push(new Data("St. Helena", "California", 89, 58, 37));
arr.push(new Data("Stallion Springs", "California", 86, 50, 12));
arr.push(new Data("Stanford", "California", 79, 58, 17));
arr.push(new Data("Stanton", "California", 85, 68, 13));
arr.push(new Data("Stevenson Ranch", "California", 92, 64, 18));
arr.push(new Data("Stevinson", "California", 94, 56, 12));
arr.push(new Data("Stinson Beach", "California", 77, 55, 41));
arr.push(new Data("Stirling City", "California", 90, 52, 65));
arr.push(new Data("Stockton", "California", 92, 55, 17));
arr.push(new Data("Stonyford", "California", 93, 56, 23));
arr.push(new Data("Stratford", "California", 96, 55, 8));
arr.push(new Data("Strathmore", "California", 96, 57, 12));
arr.push(new Data("Strawberry (Marin Cnty)", "California", 77, 55, 40));
arr.push(new Data("Suisun City", "California", 92, 56, 25));
arr.push(new Data("Sultana", "California", 95, 55, 11));
arr.push(new Data("Summerland", "California", 74, 63, 18));
arr.push(new Data("Sun Village", "California", 97, 58, 8));
arr.push(new Data("Sunny Slopes", "California", 77, 41, 15));
arr.push(new Data("Sunnyside", "California", 97, 56, 13));
arr.push(new Data("Sunnyside-Tahoe City", "California", 78, 40, 28));
arr.push(new Data("Sunnyvale", "California", 80, 58, 15));
arr.push(new Data("Sunol", "California", 85, 57, 19));
arr.push(new Data("Susanville", "California", 86, 41, 17));
arr.push(new Data("Sutter", "California", 94, 55, 21));
arr.push(new Data("Sutter Creek", "California", 93, 54, 30));
arr.push(new Data("Swall Meadows", "California", 94, 50, 5));
arr.push(new Data("Taft", "California", 96, 56, 7));
arr.push(new Data("Taft Heights", "California", 96, 56, 6));
arr.push(new Data("Taft Mosswood", "California", 92, 55, 17));
arr.push(new Data("Tahoe Vista", "California", 78, 40, 28));
arr.push(new Data("Tahoma", "California", 78, 42, 24));
arr.push(new Data("Talmage", "California", 91, 55, 41));
arr.push(new Data("Tamalpais-Homestead Valley", "California", 77, 55, 41));
arr.push(new Data("Tara Hills", "California", 78, 56, 36));
arr.push(new Data("Tarpey Village", "California", 98, 56, 13));
arr.push(new Data("Taylorsville", "California", 85, 41, 30));
arr.push(new Data("Tecopa", "California", 101, 58, 5));
arr.push(new Data("Tehachapi", "California", 86, 50, 12));
arr.push(new Data("Tehama", "California", 94, 55, 26));
arr.push(new Data("Temecula", "California", 96, 67, 12));
arr.push(new Data("Temelec", "California", 85, 57, 31));
arr.push(new Data("Temescal Valley", "California", 97, 67, 11));
arr.push(new Data("Temple City", "California", 87, 69, 16));
arr.push(new Data("Templeton", "California", 89, 60, 19));
arr.push(new Data("Tennant", "California", 86, 40, 18));
arr.push(new Data("Terminous", "California", 92, 55, 18));
arr.push(new Data("Terra Bella", "California", 97, 58, 11));
arr.push(new Data("Teviston", "California", 97, 57, 9));
arr.push(new Data("Thermal", "California", 107, 71, 3));
arr.push(new Data("Thermalito", "California", 94, 55, 34));
arr.push(new Data("Thornton", "California", 92, 55, 19));
arr.push(new Data("Thousand Oaks", "California", 90, 67, 18));
arr.push(new Data("Thousand Palms", "California", 107, 69, 5));
arr.push(new Data("Three Rivers", "California", 97, 57, 27));
arr.push(new Data("Three Rocks", "California", 95, 55, 9));
arr.push(new Data("Tiburon", "California", 77, 55, 37));
arr.push(new Data("Timber Cove", "California", 78, 56, 52));
arr.push(new Data("Tipton", "California", 96, 56, 10));
arr.push(new Data("Tomales", "California", 77, 57, 37));
arr.push(new Data("Tonyville", "California", 96, 57, 12));
arr.push(new Data("Tooleville", "California", 95, 56, 13));
arr.push(new Data("Topanga", "California", 90, 67, 19));
arr.push(new Data("Topaz", "California", 84, 43, 13));
arr.push(new Data("Toro Canyon", "California", 74, 63, 18));
arr.push(new Data("Torrance", "California", 77, 66, 14));
arr.push(new Data("Tracy", "California", 91, 56, 14));
arr.push(new Data("Tranquillity", "California", 95, 55, 11));
arr.push(new Data("Traver", "California", 94, 54, 10));
arr.push(new Data("Tres Pinos", "California", 87, 59, 15));
arr.push(new Data("Trinidad", "California", 74, 52, 56));
arr.push(new Data("Trinity Center", "California", 89, 44, 28));
arr.push(new Data("Trinity Village", "California", 95, 49, 44));
arr.push(new Data("Trowbridge", "California", 94, 54, 21));
arr.push(new Data("Truckee", "California", 83, 41, 31));
arr.push(new Data("Tulare", "California", 95, 55, 10));
arr.push(new Data("Tulelake", "California", 85, 40, 13));
arr.push(new Data("Tuolumne City", "California", 90, 52, 40));
arr.push(new Data("Tupman", "California", 97, 57, 7));
arr.push(new Data("Turlock", "California", 94, 56, 12));
arr.push(new Data("Tustin", "California", 84, 68, 13));
arr.push(new Data("Tuttle", "California", 94, 54, 12));
arr.push(new Data("Tuttletown", "California", 90, 52, 41));
arr.push(new Data("Twain Harte", "California", 85, 46, 44));
arr.push(new Data("Twentynine Palms", "California", 102, 61, 6));
arr.push(new Data("Twin Lakes", "California", 74, 61, 25));
arr.push(new Data("Ukiah", "California", 91, 55, 41));
arr.push(new Data("Union City", "California", 77, 58, 17));
arr.push(new Data("University of California Davis", "California", 93, 54, 21));
arr.push(new Data("Upland", "California", 94, 67, 21));
arr.push(new Data("Upper Lake", "California", 89, 54, 43));
arr.push(new Data("Vacaville", "California", 93, 56, 25));
arr.push(new Data("Val Verde", "California", 91, 64, 18));
arr.push(new Data("Valinda", "California", 89, 70, 15));
arr.push(new Data("Valle Vista", "California", 99, 67, 12));
arr.push(new Data("Vallecito", "California", 93, 55, 33));
arr.push(new Data("Vallejo", "California", 84, 56, 21));
arr.push(new Data("Valley Acres", "California", 96, 56, 6));
arr.push(new Data("Valley Center", "California", 90, 66, 15));
arr.push(new Data("Valley Ford", "California", 79, 56, 39));
arr.push(new Data("Valley Home", "California", 93, 55, 13));
arr.push(new Data("Valley Springs", "California", 95, 56, 28));
arr.push(new Data("Vandenberg AFB", "California", 76, 64, 16));
arr.push(new Data("Vandenberg Village", "California", 75, 64, 16));
arr.push(new Data("Ventura", "California", 77, 67, 16));
arr.push(new Data("Verdi", "California", 85, 42, 21));
arr.push(new Data("Vernon", "California", 84, 68, 15));
arr.push(new Data("Victor", "California", 92, 55, 19));
arr.push(new Data("Victorville", "California", 97, 57, 14));
arr.push(new Data("View Park-Windsor Hills", "California", 77, 65, 14));
arr.push(new Data("Villa Park", "California", 87, 68, 14));
arr.push(new Data("Vina", "California", 94, 55, 25));
arr.push(new Data("Vincent", "California", 89, 68, 17));
arr.push(new Data("Vine Hill", "California", 88, 56, 18));
arr.push(new Data("Vineyard", "California", 92, 54, 20));
arr.push(new Data("Visalia", "California", 94, 55, 11));
arr.push(new Data("Vista", "California", 82, 67, 13));
arr.push(new Data("Vista Santa Rosa", "California", 107, 71, 3));
arr.push(new Data("Volcano", "California", 91, 51, 42));
arr.push(new Data("Volta", "California", 94, 55, 10));
arr.push(new Data("Walker", "California", 74, 38, 42));
arr.push(new Data("Wallace", "California", 95, 55, 26));
arr.push(new Data("Walnut", "California", 90, 68, 16));
arr.push(new Data("Walnut Creek", "California", 86, 56, 20));
arr.push(new Data("Walnut Grove", "California", 92, 55, 19));
arr.push(new Data("Walnut Park", "California", 84, 68, 14));
arr.push(new Data("Warm Springs", "California", 99, 67, 12));
arr.push(new Data("Wasco", "California", 97, 57, 7));
arr.push(new Data("Washington", "California", 85, 47, 69));
arr.push(new Data("Waterford", "California", 93, 55, 13));
arr.push(new Data("Waterloo", "California", 92, 55, 17));
arr.push(new Data("Watsonville", "California", 74, 61, 25));
arr.push(new Data("Waukena", "California", 95, 55, 10));
arr.push(new Data("Wawona", "California", 77, 42, 36));
arr.push(new Data("Weaverville", "California", 93, 45, 37));
arr.push(new Data("Weed", "California", 87, 45, 40));
arr.push(new Data("Weedpatch", "California", 96, 57, 7));
arr.push(new Data("Weldon", "California", 92, 56, 14));
arr.push(new Data("Weott", "California", 72, 53, 56));
arr.push(new Data("West Athens", "California", 79, 66, 14));
arr.push(new Data("West Bishop", "California", 94, 50, 5));
arr.push(new Data("West Carson", "California", 80, 66, 14));
arr.push(new Data("West Covina", "California", 89, 68, 17));
arr.push(new Data("West Goshen", "California", 94, 54, 10));
arr.push(new Data("West Hollywood", "California", 80, 66, 16));
arr.push(new Data("West Menlo Park", "California", 79, 58, 17));
arr.push(new Data("West Modesto", "California", 93, 55, 13));
arr.push(new Data("West Park", "California", 96, 55, 12));
arr.push(new Data("West Point", "California", 91, 51, 43));
arr.push(new Data("West Puente Valley", "California", 89, 69, 15));
arr.push(new Data("West Rancho Dominguez", "California", 77, 66, 14));
arr.push(new Data("West Sacramento", "California", 92, 54, 20));
arr.push(new Data("West Whittier-Los Nietos", "California", 87, 69, 15));
arr.push(new Data("Westhaven-Moonstone", "California", 74, 52, 56));
arr.push(new Data("Westley", "California", 93, 56, 13));
arr.push(new Data("Westminster", "California", 83, 68, 14));
arr.push(new Data("Westmont", "California", 79, 66, 14));
arr.push(new Data("Westmorland", "California", 106, 69, 3));
arr.push(new Data("Westwood", "California", 83, 41, 41));
arr.push(new Data("Wheatland", "California", 94, 54, 21));
arr.push(new Data("Whitehawk", "California", 84, 43, 37));
arr.push(new Data("Whitewater", "California", 98, 66, 12));
arr.push(new Data("Whitley Gardens", "California", 89, 60, 18));
arr.push(new Data("Whittier", "California", 88, 69, 15));
arr.push(new Data("Wildomar", "California", 97, 67, 12));
arr.push(new Data("Wilkerson", "California", 94, 50, 5));
arr.push(new Data("Williams", "California", 94, 56, 25));
arr.push(new Data("Willits", "California", 88, 53, 47));
arr.push(new Data("Willow Creek", "California", 86, 51, 54));
arr.push(new Data("Willowbrook", "California", 77, 65, 14));
arr.push(new Data("Willows", "California", 94, 57, 24));
arr.push(new Data("Wilton", "California", 91, 55, 20));
arr.push(new Data("Winchester", "California", 99, 67, 12));
arr.push(new Data("Windsor", "California", 85, 57, 41));
arr.push(new Data("Winter Gardens", "California", 90, 69, 14));
arr.push(new Data("Winterhaven", "California", 107, 68, 4));
arr.push(new Data("Winters", "California", 95, 56, 25));
arr.push(new Data("Winton", "California", 93, 54, 13));
arr.push(new Data("Wofford Heights", "California", 94, 57, 15));
arr.push(new Data("Woodacre", "California", 79, 56, 41));
arr.push(new Data("Woodbridge", "California", 92, 55, 19));
arr.push(new Data("Woodcrest", "California", 96, 68, 11));
arr.push(new Data("Woodlake", "California", 96, 57, 13));
arr.push(new Data("Woodland", "California", 93, 54, 21));
arr.push(new Data("Woodlands", "California", 78, 64, 17));
arr.push(new Data("Woodside", "California", 83, 54, 37));
arr.push(new Data("Woodville", "California", 95, 55, 10));
arr.push(new Data("Wrightwood", "California", 82, 49, 25));
arr.push(new Data("Yankee Hill", "California", 94, 55, 34));
arr.push(new Data("Yettem", "California", 95, 56, 12));
arr.push(new Data("Yolo", "California", 93, 54, 21));
arr.push(new Data("Yorba Linda", "California", 88, 68, 15));
arr.push(new Data("Yosemite Lakes", "California", 94, 54, 28));
arr.push(new Data("Yosemite Valley", "California", 77, 42, 36));
arr.push(new Data("Yountville", "California", 86, 57, 31));
arr.push(new Data("Yreka", "California", 90, 45, 21));
arr.push(new Data("Yuba City", "California", 94, 55, 22));
arr.push(new Data("Yucaipa", "California", 98, 63, 23));
arr.push(new Data("Yucca Valley", "California", 99, 60, 8));
arr.push(new Data("Zayante", "California", 82, 60, 36));
