arr.push(new Data("Aberdeen", "Washington", 68, 47, 76));
arr.push(new Data("Aberdeen Gardens", "Washington", 68, 47, 76));
arr.push(new Data("Acme", "Washington", 73, 45, 39));
arr.push(new Data("Addy", "Washington", 86, 32, 21));
arr.push(new Data("Ahtanum", "Washington", 87, 36, 9));
arr.push(new Data("Airway Heights", "Washington", 83, 33, 17));
arr.push(new Data("Albion", "Washington", 84, 35, 21));
arr.push(new Data("Alder", "Washington", 77, 45, 52));
arr.push(new Data("Alderton", "Washington", 77, 45, 44));
arr.push(new Data("Alderwood Manor", "Washington", 75, 45, 40));
arr.push(new Data("Alger", "Washington", 74, 45, 44));
arr.push(new Data("Algona", "Washington", 76, 44, 46));
arr.push(new Data("Allyn", "Washington", 76, 45, 54));
arr.push(new Data("Almira", "Washington", 86, 32, 12));
arr.push(new Data("Altoona", "Washington", 72, 48, 100));
arr.push(new Data("Amanda Park", "Washington", 72, 43, 119));
arr.push(new Data("Amboy", "Washington", 80, 44, 66));
arr.push(new Data("Ames Lake", "Washington", 77, 45, 50));
arr.push(new Data("Anacortes", "Washington", 71, 46, 26));
arr.push(new Data("Anderson Island", "Washington", 76, 45, 48));
arr.push(new Data("Arlington", "Washington", 75, 45, 42));
arr.push(new Data("Arlington Heights", "Washington", 75, 45, 42));
arr.push(new Data("Artondale", "Washington", 76, 46, 45));
arr.push(new Data("Ashford", "Washington", 76, 41, 64));
arr.push(new Data("Asotin", "Washington", 86, 38, 16));
arr.push(new Data("Auburn", "Washington", 77, 45, 43));
arr.push(new Data("Bainbridge Island", "Washington", 76, 46, 44));
arr.push(new Data("Bangor Base", "Washington", 77, 45, 42));
arr.push(new Data("Banks Lake South", "Washington", 87, 34, 9));
arr.push(new Data("Barberton", "Washington", 80, 46, 44));
arr.push(new Data("Baring", "Washington", 74, 40, 101));
arr.push(new Data("Barney's Junction", "Washington", 88, 33, 20));
arr.push(new Data("Barstow", "Washington", 88, 33, 20));
arr.push(new Data("Basin City", "Washington", 85, 36, 9));
arr.push(new Data("Battle Ground", "Washington", 80, 44, 54));
arr.push(new Data("Bay Center", "Washington", 69, 47, 79));
arr.push(new Data("Bay View", "Washington", 74, 46, 36));
arr.push(new Data("Beaux Arts Village", "Washington", 76, 46, 38));
arr.push(new Data("Belfair", "Washington", 76, 45, 54));
arr.push(new Data("Bell Hill", "Washington", 70, 45, 23));
arr.push(new Data("Bellevue", "Washington", 76, 46, 42));
arr.push(new Data("Bellingham", "Washington", 73, 45, 39));
arr.push(new Data("Benton City", "Washington", 89, 39, 8));
arr.push(new Data("Bethel", "Washington", 76, 45, 51));
arr.push(new Data("Bickleton", "Washington", 82, 34, 17));
arr.push(new Data("Big Lake", "Washington", 73, 45, 42));
arr.push(new Data("Bingen", "Washington", 82, 38, 37));
arr.push(new Data("Birch Bay", "Washington", 72, 44, 38));
arr.push(new Data("Black Diamond", "Washington", 76, 44, 50));
arr.push(new Data("Blaine", "Washington", 72, 44, 38));
arr.push(new Data("Blyn", "Washington", 70, 45, 23));
arr.push(new Data("Bonney Lake", "Washington", 76, 44, 49));
arr.push(new Data("Bothell", "Washington", 77, 46, 41));
arr.push(new Data("Bothell East", "Washington", 76, 45, 41));
arr.push(new Data("Bothell West", "Washington", 75, 45, 41));
arr.push(new Data("Boulevard Park", "Washington", 77, 46, 39));
arr.push(new Data("Boyds", "Washington", 88, 33, 20));
arr.push(new Data("Brady", "Washington", 72, 46, 80));
arr.push(new Data("Bremerton", "Washington", 77, 45, 49));
arr.push(new Data("Brewster", "Washington", 89, 32, 13));
arr.push(new Data("Bridgeport", "Washington", 88, 33, 12));
arr.push(new Data("Brier", "Washington", 75, 45, 40));
arr.push(new Data("Brinnon", "Washington", 76, 44, 42));
arr.push(new Data("Browns Point", "Washington", 76, 46, 40));
arr.push(new Data("Brush Prairie", "Washington", 80, 45, 55));
arr.push(new Data("Bryant", "Washington", 75, 45, 42));
arr.push(new Data("Bryn Mawr-Skyway", "Washington", 77, 46, 39));
arr.push(new Data("Buckley", "Washington", 77, 44, 49));
arr.push(new Data("Bucoda", "Washington", 79, 45, 49));
arr.push(new Data("Buena", "Washington", 88, 37, 8));
arr.push(new Data("Bunk Foss", "Washington", 76, 45, 44));
arr.push(new Data("Burbank", "Washington", 89, 40, 9));
arr.push(new Data("Burien", "Washington", 77, 46, 39));
arr.push(new Data("Burley", "Washington", 76, 45, 51));
arr.push(new Data("Burlington", "Washington", 74, 46, 36));
arr.push(new Data("Camano", "Washington", 71, 45, 20));
arr.push(new Data("Camas", "Washington", 81, 45, 61));
arr.push(new Data("Canterwood", "Washington", 76, 46, 50));
arr.push(new Data("Canyon Creek", "Washington", 75, 44, 47));
arr.push(new Data("Carbonado", "Washington", 74, 43, 68));
arr.push(new Data("Carlsborg", "Washington", 70, 45, 23));
arr.push(new Data("Carnation", "Washington", 77, 45, 50));
arr.push(new Data("Carson", "Washington", 81, 41, 74));
arr.push(new Data("Cascade Valley", "Washington", 86, 34, 9));
arr.push(new Data("Cashmere", "Washington", 87, 34, 16));
arr.push(new Data("Castle Rock", "Washington", 78, 45, 61));
arr.push(new Data("Cathcart", "Washington", 75, 45, 41));
arr.push(new Data("Cathlamet", "Washington", 77, 46, 79));
arr.push(new Data("Cavalero", "Washington", 75, 45, 44));
arr.push(new Data("Centerville", "Washington", 84, 37, 15));
arr.push(new Data("Central Park", "Washington", 68, 47, 76));
arr.push(new Data("Centralia", "Washington", 79, 45, 50));
arr.push(new Data("Chain Lake", "Washington", 77, 45, 50));
arr.push(new Data("Chehalis", "Washington", 80, 45, 52));
arr.push(new Data("Chelan", "Washington", 87, 33, 12));
arr.push(new Data("Chelan Falls", "Washington", 83, 31, 17));
arr.push(new Data("Cheney", "Washington", 83, 33, 18));
arr.push(new Data("Cherry Grove", "Washington", 80, 44, 54));
arr.push(new Data("Chewelah", "Washington", 86, 32, 21));
arr.push(new Data("Chico", "Washington", 77, 45, 48));
arr.push(new Data("Chinook", "Washington", 68, 48, 81));
arr.push(new Data("Clallam Bay", "Washington", 73, 44, 97));
arr.push(new Data("Clarkston", "Washington", 88, 39, 17));
arr.push(new Data("Clarkston Heights-Vineland", "Washington", 88, 39, 17));
arr.push(new Data("Clayton", "Washington", 83, 31, 22));
arr.push(new Data("Cle Elum", "Washington", 80, 34, 28));
arr.push(new Data("Clear Lake (Pierce Cnty)", "Washington", 77, 45, 52));
arr.push(new Data("Clear Lake (Skagit Cnty)", "Washington", 75, 45, 40));
arr.push(new Data("Clearview", "Washington", 75, 45, 41));
arr.push(new Data("Cliffdell", "Washington", 88, 37, 9));
arr.push(new Data("Clinton", "Washington", 75, 45, 35));
arr.push(new Data("Clover Creek", "Washington", 77, 45, 42));
arr.push(new Data("Clyde Hill", "Washington", 76, 46, 38));
arr.push(new Data("Cohassett Beach", "Washington", 68, 47, 76));
arr.push(new Data("Colfax", "Washington", 84, 36, 19));
arr.push(new Data("College Place", "Washington", 88, 40, 17));
arr.push(new Data("Colton", "Washington", 84, 35, 21));
arr.push(new Data("Colville", "Washington", 88, 33, 20));
arr.push(new Data("Conconully", "Washington", 85, 30, 17));
arr.push(new Data("Concrete", "Washington", 76, 43, 65));
arr.push(new Data("Connell", "Washington", 86, 35, 9));
arr.push(new Data("Copalis Beach", "Washington", 69, 46, 90));
arr.push(new Data("Cosmopolis", "Washington", 72, 46, 74));
arr.push(new Data("Cottage Lake", "Washington", 76, 45, 45));
arr.push(new Data("Coulee City", "Washington", 87, 34, 9));
arr.push(new Data("Coulee Dam", "Washington", 88, 33, 12));
arr.push(new Data("Country Homes", "Washington", 84, 33, 19));
arr.push(new Data("Coupeville", "Washington", 72, 45, 20));
arr.push(new Data("Covington", "Washington", 77, 45, 45));
arr.push(new Data("Cowiche", "Washington", 87, 36, 9));
arr.push(new Data("Creston", "Washington", 84, 32, 13));
arr.push(new Data("Crocker", "Washington", 78, 46, 41));
arr.push(new Data("Curlew", "Washington", 82, 28, 17));
arr.push(new Data("Curlew Lake", "Washington", 82, 28, 17));
arr.push(new Data("Cusick", "Washington", 83, 31, 27));
arr.push(new Data("Custer", "Washington", 73, 44, 41));
arr.push(new Data("Dallesport", "Washington", 86, 40, 19));
arr.push(new Data("Danville", "Washington", 83, 29, 18));
arr.push(new Data("Darrington", "Washington", 79, 42, 77));
arr.push(new Data("Dash Point", "Washington", 76, 46, 40));
arr.push(new Data("Davenport", "Washington", 84, 32, 14));
arr.push(new Data("Dayton", "Washington", 86, 38, 16));
arr.push(new Data("Deep River", "Washington", 70, 48, 100));
arr.push(new Data("Deer Park", "Washington", 83, 32, 22));
arr.push(new Data("Deming", "Washington", 74, 42, 57));
arr.push(new Data("Des Moines", "Washington", 77, 46, 39));
arr.push(new Data("Desert Aire", "Washington", 90, 39, 8));
arr.push(new Data("Dixie", "Washington", 87, 38, 20));
arr.push(new Data("Dollars Corner", "Washington", 80, 44, 54));
arr.push(new Data("Duluth", "Washington", 80, 44, 47));
arr.push(new Data("DuPont", "Washington", 77, 45, 48));
arr.push(new Data("Duvall", "Washington", 77, 45, 58));
arr.push(new Data("East Cathlamet", "Washington", 77, 46, 79));
arr.push(new Data("East Port Orchard", "Washington", 76, 45, 46));
arr.push(new Data("East Renton Highlands", "Washington", 76, 44, 52));
arr.push(new Data("East Wenatchee", "Washington", 87, 34, 9));
arr.push(new Data("Eastmont", "Washington", 75, 45, 41));
arr.push(new Data("Easton", "Washington", 79, 35, 47));
arr.push(new Data("Eatonville", "Washington", 77, 45, 52));
arr.push(new Data("Edgewood", "Washington", 78, 46, 41));
arr.push(new Data("Edison", "Washington", 74, 46, 36));
arr.push(new Data("Edmonds", "Washington", 75, 45, 37));
arr.push(new Data("Electric City", "Washington", 86, 32, 11));
arr.push(new Data("Elk Plain", "Washington", 77, 45, 46));
arr.push(new Data("Ellensburg", "Washington", 84, 34, 9));
arr.push(new Data("Elma", "Washington", 78, 45, 74));
arr.push(new Data("Elmer City", "Washington", 88, 33, 12));
arr.push(new Data("Endicott", "Washington", 86, 37, 17));
arr.push(new Data("Enetai", "Washington", 76, 45, 47));
arr.push(new Data("Entiat", "Washington", 83, 31, 24));
arr.push(new Data("Enumclaw", "Washington", 76, 44, 63));
arr.push(new Data("Ephrata", "Washington", 87, 34, 8));
arr.push(new Data("Erlands Point-Kitsap Lake", "Washington", 77, 45, 50));
arr.push(new Data("Eschbach", "Washington", 87, 36, 9));
arr.push(new Data("Esperance", "Washington", 75, 45, 37));
arr.push(new Data("Everett", "Washington", 75, 45, 42));
arr.push(new Data("Everson", "Washington", 74, 44, 40));
arr.push(new Data("Fairchild AFB", "Washington", 83, 33, 18));
arr.push(new Data("Fairfield", "Washington", 83, 34, 18));
arr.push(new Data("Fairwood (King Cnty)", "Washington", 76, 44, 52));
arr.push(new Data("Fairwood (Spokane Cnty)", "Washington", 84, 33, 19));
arr.push(new Data("Fall City", "Washington", 77, 45, 51));
arr.push(new Data("Farmington", "Washington", 83, 35, 24));
arr.push(new Data("Federal Way", "Washington", 76, 46, 41));
arr.push(new Data("Felida", "Washington", 80, 46, 44));
arr.push(new Data("Fern Prairie", "Washington", 81, 45, 62));
arr.push(new Data("Ferndale", "Washington", 72, 45, 37));
arr.push(new Data("Fife", "Washington", 77, 46, 41));
arr.push(new Data("Fife Heights", "Washington", 77, 46, 40));
arr.push(new Data("Finley", "Washington", 89, 39, 8));
arr.push(new Data("Fircrest", "Washington", 77, 46, 41));
arr.push(new Data("Five Corners", "Washington", 80, 46, 44));
arr.push(new Data("Fobes Hill", "Washington", 77, 45, 50));
arr.push(new Data("Fords Prairie", "Washington", 79, 45, 50));
arr.push(new Data("Forks", "Washington", 72, 45, 110));
arr.push(new Data("Fort Lewis", "Washington", 77, 45, 48));
arr.push(new Data("Four Lakes", "Washington", 83, 33, 18));
arr.push(new Data("Fox Island", "Washington", 76, 46, 45));
arr.push(new Data("Frederickson", "Washington", 77, 45, 42));
arr.push(new Data("Freeland", "Washington", 74, 46, 23));
arr.push(new Data("Friday Harbor", "Washington", 72, 46, 27));
arr.push(new Data("Garfield", "Washington", 83, 35, 22));
arr.push(new Data("Garrett", "Washington", 88, 40, 19));
arr.push(new Data("Geneva", "Washington", 73, 43, 53));
arr.push(new Data("George", "Washington", 86, 33, 8));
arr.push(new Data("Gig Harbor", "Washington", 76, 46, 46));
arr.push(new Data("Glacier", "Washington", 75, 41, 65));
arr.push(new Data("Gleed", "Washington", 87, 36, 9));
arr.push(new Data("Gold Bar", "Washington", 77, 44, 70));
arr.push(new Data("Goldendale", "Washington", 84, 37, 15));
arr.push(new Data("Gorst", "Washington", 77, 45, 51));
arr.push(new Data("Graham", "Washington", 76, 45, 52));
arr.push(new Data("Grand Coulee", "Washington", 86, 32, 11));
arr.push(new Data("Grand Mound", "Washington", 79, 45, 50));
arr.push(new Data("Grandview", "Washington", 89, 38, 8));
arr.push(new Data("Granger", "Washington", 89, 38, 8));
arr.push(new Data("Granite Falls", "Washington", 76, 44, 55));
arr.push(new Data("Grapeview", "Washington", 77, 45, 56));
arr.push(new Data("Grayland", "Washington", 68, 47, 76));
arr.push(new Data("Grays River", "Washington", 72, 48, 100));
arr.push(new Data("Green Bluff", "Washington", 84, 33, 19));
arr.push(new Data("Greenwater", "Washington", 76, 44, 63));
arr.push(new Data("Hamilton", "Washington", 75, 44, 51));
arr.push(new Data("Hansville", "Washington", 76, 45, 31));
arr.push(new Data("Harrah", "Washington", 88, 37, 8));
arr.push(new Data("Harrington", "Washington", 84, 32, 13));
arr.push(new Data("Hartline", "Washington", 86, 33, 12));
arr.push(new Data("Hat Island", "Washington", 75, 45, 44));
arr.push(new Data("Hatton", "Washington", 86, 35, 9));
arr.push(new Data("Hazel Dell", "Washington", 80, 46, 44));
arr.push(new Data("High Bridge", "Washington", 76, 45, 45));
arr.push(new Data("Hobart", "Washington", 76, 44, 53));
arr.push(new Data("Hockinson", "Washington", 80, 45, 58));
arr.push(new Data("Home", "Washington", 77, 45, 50));
arr.push(new Data("Hoodsport", "Washington", 76, 43, 92));
arr.push(new Data("Hoquiam", "Washington", 69, 46, 88));
arr.push(new Data("Humptulips", "Washington", 72, 43, 118));
arr.push(new Data("Hunts Point", "Washington", 76, 46, 38));
arr.push(new Data("Ilwaco", "Washington", 68, 48, 86));
arr.push(new Data("Inchelium", "Washington", 87, 33, 21));
arr.push(new Data("Index", "Washington", 77, 44, 73));
arr.push(new Data("Indianola", "Washington", 77, 45, 42));
arr.push(new Data("Ione", "Washington", 86, 33, 24));
arr.push(new Data("Issaquah", "Washington", 76, 44, 53));
arr.push(new Data("Jamestown", "Washington", 70, 45, 23));
arr.push(new Data("Kahlotus", "Washington", 88, 36, 10));
arr.push(new Data("Kalama", "Washington", 79, 43, 55));
arr.push(new Data("Kapowsin", "Washington", 76, 44, 56));
arr.push(new Data("Keller", "Washington", 86, 32, 13));
arr.push(new Data("Kelso", "Washington", 78, 44, 60));
arr.push(new Data("Kendall", "Washington", 75, 42, 59));
arr.push(new Data("Kenmore", "Washington", 77, 46, 41));
arr.push(new Data("Kennewick", "Washington", 89, 39, 8));
arr.push(new Data("Kent", "Washington", 77, 45, 43));
arr.push(new Data("Kettle Falls", "Washington", 88, 33, 20));
arr.push(new Data("Key Center", "Washington", 76, 45, 50));
arr.push(new Data("Keyport", "Washington", 77, 45, 44));
arr.push(new Data("Kingston", "Washington", 77, 45, 40));
arr.push(new Data("Kirkland", "Washington", 77, 46, 41));
arr.push(new Data("Kittitas", "Washington", 84, 34, 9));
arr.push(new Data("Klickitat", "Washington", 85, 39, 19));
arr.push(new Data("Krupp", "Washington", 87, 35, 10));
arr.push(new Data("La Center", "Washington", 80, 44, 62));
arr.push(new Data("La Conner", "Washington", 74, 46, 32));
arr.push(new Data("La Grande", "Washington", 77, 45, 52));
arr.push(new Data("Lacey", "Washington", 77, 45, 49));
arr.push(new Data("LaCrosse", "Washington", 87, 37, 17));
arr.push(new Data("Lake Bosworth", "Washington", 76, 45, 52));
arr.push(new Data("Lake Cassidy", "Washington", 75, 45, 44));
arr.push(new Data("Lake Cavanaugh", "Washington", 73, 45, 42));
arr.push(new Data("Lake Forest Park", "Washington", 75, 46, 37));
arr.push(new Data("Lake Holm", "Washington", 76, 44, 46));
arr.push(new Data("Lake Ketchum", "Washington", 75, 46, 37));
arr.push(new Data("Lake Marcel-Stillwater", "Washington", 77, 45, 50));
arr.push(new Data("Lake McMurray", "Washington", 73, 45, 42));
arr.push(new Data("Lake Morton-Berrydale", "Washington", 77, 45, 45));
arr.push(new Data("Lake Roesiger", "Washington", 77, 45, 50));
arr.push(new Data("Lake Shore", "Washington", 80, 46, 44));
arr.push(new Data("Lake Stevens", "Washington", 75, 45, 44));
arr.push(new Data("Lake Stickney", "Washington", 75, 45, 40));
arr.push(new Data("Lake Tapps", "Washington", 76, 44, 49));
arr.push(new Data("Lakeland North", "Washington", 76, 44, 45));
arr.push(new Data("Lakeland South", "Washington", 76, 45, 44));
arr.push(new Data("Lakeview", "Washington", 87, 34, 8));
arr.push(new Data("Lakewood", "Washington", 77, 46, 41));
arr.push(new Data("Lamont", "Washington", 84, 35, 17));
arr.push(new Data("Langley", "Washington", 74, 46, 29));
arr.push(new Data("Larch Way", "Washington", 74, 45, 38));
arr.push(new Data("Latah", "Washington", 83, 34, 20));
arr.push(new Data("Leavenworth", "Washington", 82, 33, 29));
arr.push(new Data("Lebam", "Washington", 72, 47, 98));
arr.push(new Data("Lewisville", "Washington", 80, 44, 54));
arr.push(new Data("Liberty Lake", "Washington", 83, 34, 20));
arr.push(new Data("Lind", "Washington", 87, 35, 11));
arr.push(new Data("Lochsloy", "Washington", 75, 45, 45));
arr.push(new Data("Lofall", "Washington", 77, 45, 41));
arr.push(new Data("Long Beach", "Washington", 68, 48, 86));
arr.push(new Data("Longbranch", "Washington", 77, 45, 50));
arr.push(new Data("Longview", "Washington", 78, 44, 56));
arr.push(new Data("Longview Heights", "Washington", 78, 44, 56));
arr.push(new Data("Loomis", "Washington", 82, 31, 15));
arr.push(new Data("Loon Lake", "Washington", 84, 32, 20));
arr.push(new Data("Lower Elochoman", "Washington", 77, 46, 79));
arr.push(new Data("Lyle", "Washington", 84, 38, 22));
arr.push(new Data("Lyman", "Washington", 75, 44, 49));
arr.push(new Data("Lynden", "Washington", 74, 43, 42));
arr.push(new Data("Lynnwood", "Washington", 75, 45, 38));
arr.push(new Data("Mabton", "Washington", 89, 38, 8));
arr.push(new Data("Machias", "Washington", 76, 45, 47));
arr.push(new Data("Malden", "Washington", 84, 35, 18));
arr.push(new Data("Malo", "Washington", 83, 29, 18));
arr.push(new Data("Malone", "Washington", 78, 45, 73));
arr.push(new Data("Malott", "Washington", 87, 31, 14));
arr.push(new Data("Maltby", "Washington", 75, 45, 42));
arr.push(new Data("Manchester", "Washington", 76, 45, 46));
arr.push(new Data("Mansfield", "Washington", 85, 31, 12));
arr.push(new Data("Manson", "Washington", 87, 33, 13));
arr.push(new Data("Maple Falls", "Washington", 75, 41, 63));
arr.push(new Data("Maple Heights-Lake Desire", "Washington", 76, 44, 52));
arr.push(new Data("Maple Valley", "Washington", 76, 44, 53));
arr.push(new Data("Maplewood", "Washington", 76, 46, 50));
arr.push(new Data("Marcus", "Washington", 88, 33, 20));
arr.push(new Data("Marietta-Alderwood", "Washington", 72, 45, 34));
arr.push(new Data("Markham", "Washington", 68, 47, 76));
arr.push(new Data("Marrowstone", "Washington", 72, 46, 23));
arr.push(new Data("Martha Lake", "Washington", 75, 45, 40));
arr.push(new Data("Marysville", "Washington", 76, 45, 45));
arr.push(new Data("Mattawa", "Washington", 90, 39, 8));
arr.push(new Data("May Creek", "Washington", 77, 44, 70));
arr.push(new Data("McChord AFB", "Washington", 77, 46, 41));
arr.push(new Data("McCleary", "Washington", 78, 45, 74));
arr.push(new Data("McKenna", "Washington", 76, 45, 46));
arr.push(new Data("McMillin", "Washington", 78, 46, 41));
arr.push(new Data("Mead", "Washington", 84, 33, 19));
arr.push(new Data("Meadow Glade", "Washington", 80, 44, 54));
arr.push(new Data("Meadowdale", "Washington", 75, 45, 37));
arr.push(new Data("Medical Lake", "Washington", 83, 33, 18));
arr.push(new Data("Medina", "Washington", 76, 46, 38));
arr.push(new Data("Mercer Island", "Washington", 77, 46, 39));
arr.push(new Data("Mesa", "Washington", 85, 36, 9));
arr.push(new Data("Metaline", "Washington", 84, 32, 27));
arr.push(new Data("Metaline Falls", "Washington", 84, 32, 27));
arr.push(new Data("Methow", "Washington", 88, 33, 12));
arr.push(new Data("Midland", "Washington", 77, 46, 42));
arr.push(new Data("Mill Creek", "Washington", 75, 45, 41));
arr.push(new Data("Mill Creek East", "Washington", 75, 45, 41));
arr.push(new Data("Millwood", "Washington", 83, 34, 18));
arr.push(new Data("Milton", "Washington", 77, 46, 41));
arr.push(new Data("Mineral", "Washington", 75, 36, 80));
arr.push(new Data("Minnehaha", "Washington", 81, 46, 39));
arr.push(new Data("Mirrormont", "Washington", 76, 44, 53));
arr.push(new Data("Monroe", "Washington", 77, 45, 51));
arr.push(new Data("Monroe North", "Washington", 77, 45, 50));
arr.push(new Data("Montesano", "Washington", 72, 46, 80));
arr.push(new Data("Morton", "Washington", 79, 43, 61));
arr.push(new Data("Moses Lake", "Washington", 86, 34, 9));
arr.push(new Data("Moses Lake North", "Washington", 86, 34, 9));
arr.push(new Data("Mossyrock", "Washington", 79, 44, 61));
arr.push(new Data("Mount Vernon", "Washington", 74, 46, 38));
arr.push(new Data("Mount Vista", "Washington", 80, 45, 45));
arr.push(new Data("Mountlake Terrace", "Washington", 75, 45, 37));
arr.push(new Data("Moxee", "Washington", 87, 36, 9));
arr.push(new Data("Mukilteo", "Washington", 75, 45, 40));
arr.push(new Data("Naches", "Washington", 88, 37, 9));
arr.push(new Data("Napavine", "Washington", 80, 45, 52));
arr.push(new Data("Naselle", "Washington", 70, 48, 100));
arr.push(new Data("Navy Yard City", "Washington", 77, 45, 50));
arr.push(new Data("Neah Bay", "Washington", 72, 44, 104));
arr.push(new Data("Neilton", "Washington", 72, 43, 120));
arr.push(new Data("Nespelem", "Washington", 88, 33, 12));
arr.push(new Data("Nespelem Community", "Washington", 88, 33, 12));
arr.push(new Data("Newcastle", "Washington", 76, 45, 46));
arr.push(new Data("Newport", "Washington", 83, 31, 27));
arr.push(new Data("Nile", "Washington", 88, 37, 9));
arr.push(new Data("Nisqually Indian Community", "Washington", 77, 44, 48));
arr.push(new Data("Nooksack", "Washington", 74, 44, 40));
arr.push(new Data("Normandy Park", "Washington", 77, 46, 39));
arr.push(new Data("North Bend", "Washington", 76, 44, 67));
arr.push(new Data("North Bonneville", "Washington", 81, 44, 71));
arr.push(new Data("North Fort Lewis", "Washington", 77, 45, 48));
arr.push(new Data("North Lynnwood", "Washington", 75, 45, 40));
arr.push(new Data("North Marysville", "Washington", 75, 45, 44));
arr.push(new Data("North Omak", "Washington", 88, 33, 13));
arr.push(new Data("North Puyallup", "Washington", 78, 46, 41));
arr.push(new Data("North Sultan", "Washington", 77, 45, 52));
arr.push(new Data("North Yelm", "Washington", 76, 45, 48));
arr.push(new Data("Northport", "Washington", 87, 33, 23));
arr.push(new Data("Northwest Stanwood", "Washington", 75, 46, 37));
arr.push(new Data("Oak Harbor", "Washington", 71, 45, 20));
arr.push(new Data("Oakesdale", "Washington", 83, 35, 18));
arr.push(new Data("Oakville", "Washington", 79, 46, 52));
arr.push(new Data("Ocean City", "Washington", 68, 47, 77));
arr.push(new Data("Ocean Park", "Washington", 68, 47, 91));
arr.push(new Data("Ocean Shores", "Washington", 68, 47, 75));
arr.push(new Data("Odessa", "Washington", 87, 35, 12));
arr.push(new Data("Okanogan", "Washington", 89, 32, 13));
arr.push(new Data("Olympia", "Washington", 78, 45, 53));
arr.push(new Data("Omak", "Washington", 88, 33, 13));
arr.push(new Data("Onalaska", "Washington", 79, 45, 56));
arr.push(new Data("Orchards", "Washington", 80, 45, 44));
arr.push(new Data("Orient", "Washington", 82, 28, 17));
arr.push(new Data("Oroville", "Washington", 87, 32, 15));
arr.push(new Data("Orting", "Washington", 78, 46, 41));
arr.push(new Data("Oso", "Washington", 75, 45, 42));
arr.push(new Data("Othello", "Washington", 86, 35, 9));
arr.push(new Data("Otis Orchards-East Farms", "Washington", 83, 34, 22));
arr.push(new Data("Pacific", "Washington", 78, 46, 40));
arr.push(new Data("Pacific Beach", "Washington", 70, 45, 99));
arr.push(new Data("Packwood", "Washington", 77, 43, 62));
arr.push(new Data("Palouse", "Washington", 84, 35, 21));
arr.push(new Data("Parker", "Washington", 88, 36, 8));
arr.push(new Data("Parkland", "Washington", 77, 46, 42));
arr.push(new Data("Parkwood", "Washington", 76, 45, 46));
arr.push(new Data("Pasco", "Washington", 89, 39, 8));
arr.push(new Data("Pateros", "Washington", 86, 31, 18));
arr.push(new Data("Pe Ell", "Washington", 79, 46, 66));
arr.push(new Data("Peaceful Valley", "Washington", 75, 42, 59));
arr.push(new Data("Picnic Point", "Washington", 75, 45, 38));
arr.push(new Data("Pine Grove", "Washington", 82, 28, 17));
arr.push(new Data("Point Roberts", "Washington", 72, 44, 36));
arr.push(new Data("Pomeroy", "Washington", 84, 36, 19));
arr.push(new Data("Port Angeles", "Washington", 70, 43, 36));
arr.push(new Data("Port Angeles East", "Washington", 70, 43, 35));
arr.push(new Data("Port Gamble Tribal Community", "Washington", 77, 45, 40));
arr.push(new Data("Port Hadlock-Irondale", "Washington", 73, 45, 23));
arr.push(new Data("Port Ludlow", "Washington", 75, 45, 24));
arr.push(new Data("Port Orchard", "Washington", 76, 45, 47));
arr.push(new Data("Port Townsend", "Washington", 72, 46, 23));
arr.push(new Data("Porter", "Washington", 78, 45, 74));
arr.push(new Data("Poulsbo", "Washington", 77, 45, 41));
arr.push(new Data("Prairie Heights", "Washington", 77, 44, 49));
arr.push(new Data("Prairie Ridge", "Washington", 76, 44, 49));
arr.push(new Data("Prescott", "Washington", 88, 39, 16));
arr.push(new Data("Prosser", "Washington", 88, 38, 9));
arr.push(new Data("Puget Island", "Washington", 77, 46, 79));
arr.push(new Data("Pullman", "Washington", 84, 35, 21));
arr.push(new Data("Purdy", "Washington", 76, 46, 50));
arr.push(new Data("Puyallup", "Washington", 78, 46, 41));
arr.push(new Data("Queets", "Washington", 72, 45, 110));
arr.push(new Data("Quilcene", "Washington", 76, 45, 33));
arr.push(new Data("Qui-nai-elt Village", "Washington", 70, 45, 100));
arr.push(new Data("Quincy", "Washington", 86, 33, 8));
arr.push(new Data("Raft Island", "Washington", 76, 46, 45));
arr.push(new Data("Rainier", "Washington", 78, 45, 49));
arr.push(new Data("Ravensdale", "Washington", 76, 44, 64));
arr.push(new Data("Raymond", "Washington", 72, 47, 98));
arr.push(new Data("Reardan", "Washington", 84, 32, 16));
arr.push(new Data("Redmond", "Washington", 77, 46, 41));
arr.push(new Data("Renton", "Washington", 77, 45, 44));
arr.push(new Data("Republic", "Washington", 82, 28, 17));
arr.push(new Data("Richland", "Washington", 89, 39, 8));
arr.push(new Data("Ridgefield", "Washington", 80, 44, 47));
arr.push(new Data("Ritzville", "Washington", 86, 34, 12));
arr.push(new Data("River Road", "Washington", 70, 45, 23));
arr.push(new Data("Riverbend", "Washington", 76, 44, 67));
arr.push(new Data("Riverside", "Washington", 86, 31, 14));
arr.push(new Data("Rochester", "Washington", 79, 45, 51));
arr.push(new Data("Rock Island", "Washington", 85, 33, 14));
arr.push(new Data("Rockford", "Washington", 83, 34, 18));
arr.push(new Data("Rockport", "Washington", 77, 41, 74));
arr.push(new Data("Rocky Point", "Washington", 77, 45, 50));
arr.push(new Data("Ronald", "Washington", 80, 34, 30));
arr.push(new Data("Roosevelt", "Washington", 85, 38, 14));
arr.push(new Data("Rosalia", "Washington", 84, 34, 18));
arr.push(new Data("Rosburg", "Washington", 72, 48, 100));
arr.push(new Data("Rosedale", "Washington", 76, 46, 50));
arr.push(new Data("Roslyn", "Washington", 80, 34, 29));
arr.push(new Data("Roy", "Washington", 76, 45, 46));
arr.push(new Data("Royal City", "Washington", 88, 36, 8));
arr.push(new Data("Ruston", "Washington", 77, 46, 41));
arr.push(new Data("Ryderwood", "Washington", 80, 45, 63));
arr.push(new Data("Salmon Creek", "Washington", 80, 46, 44));
arr.push(new Data("Sammamish", "Washington", 76, 45, 53));
arr.push(new Data("Santiago", "Washington", 70, 45, 100));
arr.push(new Data("Satsop", "Washington", 78, 45, 73));
arr.push(new Data("Seabeck", "Washington", 77, 45, 49));
arr.push(new Data("SeaTac", "Washington", 77, 46, 39));
arr.push(new Data("Seattle", "Washington", 76, 46, 38));
arr.push(new Data("Sedro-Woolley", "Washington", 75, 44, 49));
arr.push(new Data("Selah", "Washington", 88, 37, 9));
arr.push(new Data("Sequim", "Washington", 70, 45, 23));
arr.push(new Data("Shadow Lake", "Washington", 76, 44, 52));
arr.push(new Data("Shelton", "Washington", 77, 45, 62));
arr.push(new Data("Shoreline", "Washington", 75, 46, 37));
arr.push(new Data("Silver Firs", "Washington", 75, 45, 41));
arr.push(new Data("Silverdale", "Washington", 77, 45, 43));
arr.push(new Data("Sisco Heights", "Washington", 75, 45, 42));
arr.push(new Data("Skamokawa Valley", "Washington", 74, 47, 97));
arr.push(new Data("Skokomish", "Washington", 77, 45, 62));
arr.push(new Data("Skykomish", "Washington", 74, 41, 102));
arr.push(new Data("Snohomish", "Washington", 77, 45, 50));
arr.push(new Data("Snoqualmie", "Washington", 76, 44, 54));
arr.push(new Data("Snoqualmie Pass", "Washington", 76, 43, 74));
arr.push(new Data("Soap Lake", "Washington", 87, 34, 8));
arr.push(new Data("South Bend", "Washington", 72, 47, 90));
arr.push(new Data("South Cle Elum", "Washington", 80, 34, 28));
arr.push(new Data("South Creek", "Washington", 77, 45, 47));
arr.push(new Data("South Hill", "Washington", 77, 45, 43));
arr.push(new Data("South Prairie", "Washington", 77, 44, 49));
arr.push(new Data("South Wenatchee", "Washington", 87, 34, 9));
arr.push(new Data("Southworth", "Washington", 76, 45, 46));
arr.push(new Data("Spanaway", "Washington", 77, 45, 42));
arr.push(new Data("Spangle", "Washington", 83, 34, 18));
arr.push(new Data("Spokane", "Washington", 83, 33, 17));
arr.push(new Data("Spokane Valley", "Washington", 84, 34, 20));
arr.push(new Data("Sprague", "Washington", 84, 34, 16));
arr.push(new Data("Springdale", "Washington", 84, 32, 18));
arr.push(new Data("St. John", "Washington", 85, 36, 18));
arr.push(new Data("Stansberry Lake", "Washington", 76, 45, 50));
arr.push(new Data("Stanwood", "Washington", 75, 46, 37));
arr.push(new Data("Starbuck", "Washington", 87, 38, 15));
arr.push(new Data("Startup", "Washington", 77, 45, 52));
arr.push(new Data("Steilacoom", "Washington", 77, 46, 44));
arr.push(new Data("Steptoe", "Washington", 84, 36, 19));
arr.push(new Data("Stevenson", "Washington", 81, 43, 66));
arr.push(new Data("Sudden Valley", "Washington", 73, 43, 53));
arr.push(new Data("Sultan", "Washington", 77, 45, 52));
arr.push(new Data("Sumas", "Washington", 74, 44, 40));
arr.push(new Data("Summit", "Washington", 77, 46, 41));
arr.push(new Data("Summit View", "Washington", 77, 45, 42));
arr.push(new Data("Summitview", "Washington", 87, 36, 9));
arr.push(new Data("Sumner", "Washington", 76, 44, 49));
arr.push(new Data("Sunday Lake", "Washington", 75, 46, 37));
arr.push(new Data("Sunnyside", "Washington", 89, 38, 8));
arr.push(new Data("Sunnyslope", "Washington", 87, 34, 9));
arr.push(new Data("Suquamish", "Washington", 77, 46, 43));
arr.push(new Data("Swede Heaven", "Washington", 75, 45, 42));
arr.push(new Data("Tacoma", "Washington", 77, 46, 41));
arr.push(new Data("Taholah", "Washington", 70, 45, 100));
arr.push(new Data("Tampico", "Washington", 87, 36, 9));
arr.push(new Data("Tanglewilde", "Washington", 77, 45, 49));
arr.push(new Data("Tanner", "Washington", 76, 44, 67));
arr.push(new Data("Tekoa", "Washington", 83, 34, 20));
arr.push(new Data("Tenino", "Washington", 79, 45, 49));
arr.push(new Data("Terrace Heights", "Washington", 88, 37, 9));
arr.push(new Data("Thorp", "Washington", 68, 31, 81));
arr.push(new Data("Three Lakes", "Washington", 77, 45, 50));
arr.push(new Data("Tieton", "Washington", 84, 34, 13));
arr.push(new Data("Tokeland", "Washington", 69, 47, 76));
arr.push(new Data("Toledo", "Washington", 80, 45, 52));
arr.push(new Data("Tonasket", "Washington", 86, 32, 14));
arr.push(new Data("Toppenish", "Washington", 89, 37, 8));
arr.push(new Data("Torboy", "Washington", 82, 28, 17));
arr.push(new Data("Touchet", "Washington", 88, 41, 14));
arr.push(new Data("Town and Country", "Washington", 83, 33, 17));
arr.push(new Data("Tracyton", "Washington", 77, 45, 45));
arr.push(new Data("Trout Lake", "Washington", 82, 36, 38));
arr.push(new Data("Tukwila", "Washington", 77, 46, 39));
arr.push(new Data("Tumwater", "Washington", 79, 45, 50));
arr.push(new Data("Twin Lakes", "Washington", 87, 33, 21));
arr.push(new Data("Twisp", "Washington", 84, 29, 17));
arr.push(new Data("Union", "Washington", 76, 44, 70));
arr.push(new Data("Union Gap", "Washington", 87, 36, 9));
arr.push(new Data("Union Hill-Novelty Hill", "Washington", 77, 45, 50));
arr.push(new Data("Uniontown", "Washington", 84, 35, 22));
arr.push(new Data("University Place", "Washington", 77, 46, 41));
arr.push(new Data("Upper Elochoman", "Washington", 77, 46, 79));
arr.push(new Data("Vader", "Washington", 80, 45, 62));
arr.push(new Data("Valley", "Washington", 86, 32, 21));
arr.push(new Data("Vancouver", "Washington", 80, 46, 42));
arr.push(new Data("Vantage", "Washington", 85, 35, 9));
arr.push(new Data("Vashon", "Washington", 77, 46, 40));
arr.push(new Data("Vaughn", "Washington", 76, 45, 50));
arr.push(new Data("Venersborg", "Washington", 80, 44, 54));
arr.push(new Data("Verlot", "Washington", 76, 44, 55));
arr.push(new Data("Waitsburg", "Washington", 87, 38, 20));
arr.push(new Data("Walla Walla", "Washington", 88, 40, 19));
arr.push(new Data("Walla Walla East", "Washington", 88, 40, 19));
arr.push(new Data("Waller", "Washington", 78, 46, 41));
arr.push(new Data("Wallula", "Washington", 89, 40, 9));
arr.push(new Data("Walnut Grove", "Washington", 80, 46, 42));
arr.push(new Data("Wapato", "Washington", 88, 36, 8));
arr.push(new Data("Warden", "Washington", 86, 35, 9));
arr.push(new Data("Warm Beach", "Washington", 75, 46, 37));
arr.push(new Data("Washougal", "Washington", 80, 44, 71));
arr.push(new Data("Washtucna", "Washington", 87, 36, 12));
arr.push(new Data("Waterville", "Washington", 82, 29, 18));
arr.push(new Data("Wauna", "Washington", 76, 45, 50));
arr.push(new Data("Waverly", "Washington", 83, 34, 18));
arr.push(new Data("Wenatchee", "Washington", 87, 34, 9));
arr.push(new Data("West Clarkston-Highland", "Washington", 88, 39, 17));
arr.push(new Data("West Pasco", "Washington", 89, 39, 8));
arr.push(new Data("West Richland", "Washington", 87, 38, 9));
arr.push(new Data("West Side Highway", "Washington", 78, 44, 59));
arr.push(new Data("Westport", "Washington", 68, 47, 76));
arr.push(new Data("Whidbey Island Station", "Washington", 71, 46, 22));
arr.push(new Data("White Center", "Washington", 76, 46, 39));
arr.push(new Data("White Salmon", "Washington", 82, 39, 27));
arr.push(new Data("White Swan", "Washington", 88, 37, 8));
arr.push(new Data("Wilbur", "Washington", 85, 32, 13));
arr.push(new Data("Wilderness Rim", "Washington", 76, 44, 67));
arr.push(new Data("Wilkeson", "Washington", 74, 43, 68));
arr.push(new Data("Willapa", "Washington", 72, 47, 98));
arr.push(new Data("Wilson Creek", "Washington", 87, 35, 9));
arr.push(new Data("Winlock", "Washington", 80, 45, 52));
arr.push(new Data("Winthrop", "Washington", 84, 29, 21));
arr.push(new Data("Wishram", "Washington", 84, 37, 15));
arr.push(new Data("Wollochet", "Washington", 76, 46, 45));
arr.push(new Data("Woodinville", "Washington", 75, 45, 40));
arr.push(new Data("Woodland", "Washington", 80, 44, 61));
arr.push(new Data("Woods Creek", "Washington", 77, 45, 51));
arr.push(new Data("Woodway", "Washington", 75, 46, 37));
arr.push(new Data("Yacolt", "Washington", 80, 42, 79));
arr.push(new Data("Yakima", "Washington", 87, 36, 9));
arr.push(new Data("Yarrow Point", "Washington", 76, 46, 38));
arr.push(new Data("Yelm", "Washington", 76, 45, 48));
arr.push(new Data("Zillah", "Washington", 88, 37, 8));
